// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: error.proto

package errorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cause int32

const (
	/// Streaming cannot be started due to resource limitation (e.g. no free websockets)
	Cause_RESOURCE_LIMIT Cause = 0
)

// Enum value maps for Cause.
var (
	Cause_name = map[int32]string{
		0: "RESOURCE_LIMIT",
	}
	Cause_value = map[string]int32{
		"RESOURCE_LIMIT": 0,
	}
)

func (x Cause) Enum() *Cause {
	p := new(Cause)
	*p = x
	return p
}

func (x Cause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cause) Descriptor() protoreflect.EnumDescriptor {
	return file_error_proto_enumTypes[0].Descriptor()
}

func (Cause) Type() protoreflect.EnumType {
	return &file_error_proto_enumTypes[0]
}

func (x Cause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cause.Descriptor instead.
func (Cause) EnumDescriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_FATAL   Severity = 0
	Severity_ERROR   Severity = 1
	Severity_WARNING Severity = 2
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "FATAL",
		1: "ERROR",
		2: "WARNING",
	}
	Severity_value = map[string]int32{
		"FATAL":   0,
		"ERROR":   1,
		"WARNING": 2,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_error_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_error_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{1}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cause         Cause                  `protobuf:"varint,1,opt,name=cause,proto3,enum=BSB_Error.Cause" json:"cause,omitempty"`
	Severity      Severity               `protobuf:"varint,2,opt,name=severity,proto3,enum=BSB_Error.Severity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCause() Cause {
	if x != nil {
		return x.Cause
	}
	return Cause_RESOURCE_LIMIT
}

func (x *Error) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_FATAL
}

var File_error_proto protoreflect.FileDescriptor

const file_error_proto_rawDesc = "" +
	"\n" +
	"\verror.proto\x12\tBSB_Error\"`\n" +
	"\x05Error\x12&\n" +
	"\x05cause\x18\x01 \x01(\x0e2\x10.BSB_Error.CauseR\x05cause\x12/\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x13.BSB_Error.SeverityR\bseverity*\x1b\n" +
	"\x05Cause\x12\x12\n" +
	"\x0eRESOURCE_LIMIT\x10\x00*-\n" +
	"\bSeverity\x12\t\n" +
	"\x05FATAL\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02b\x06proto3"

var (
	file_error_proto_rawDescOnce sync.Once
	file_error_proto_rawDescData []byte
)

func file_error_proto_rawDescGZIP() []byte {
	file_error_proto_rawDescOnce.Do(func() {
		file_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)))
	})
	return file_error_proto_rawDescData
}

var file_error_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_error_proto_goTypes = []any{
	(Cause)(0),    // 0: BSB_Error.Cause
	(Severity)(0), // 1: BSB_Error.Severity
	(*Error)(nil), // 2: BSB_Error.Error
}
var file_error_proto_depIdxs = []int32{
	0, // 0: BSB_Error.Error.cause:type_name -> BSB_Error.Cause
	1, // 1: BSB_Error.Error.severity:type_name -> BSB_Error.Severity
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_error_proto_init() }
func file_error_proto_init() {
	if File_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_proto_goTypes,
		DependencyIndexes: file_error_proto_depIdxs,
		EnumInfos:         file_error_proto_enumTypes,
		MessageInfos:      file_error_proto_msgTypes,
	}.Build()
	File_error_proto = out.File
	file_error_proto_goTypes = nil
	file_error_proto_depIdxs = nil
}
