// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: state/audio.proto

package statepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        uint32                 `protobuf:"varint,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioVolume) Reset() {
	*x = AudioVolume{}
	mi := &file_state_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioVolume) ProtoMessage() {}

func (x *AudioVolume) ProtoReflect() protoreflect.Message {
	mi := &file_state_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioVolume.ProtoReflect.Descriptor instead.
func (*AudioVolume) Descriptor() ([]byte, []int) {
	return file_state_audio_proto_rawDescGZIP(), []int{0}
}

func (x *AudioVolume) GetVolume() uint32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

var File_state_audio_proto protoreflect.FileDescriptor

const file_state_audio_proto_rawDesc = "" +
	"\n" +
	"\x11state/audio.proto\x12\tBSB_State\"%\n" +
	"\vAudioVolume\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\rR\x06volumeb\x06proto3"

var (
	file_state_audio_proto_rawDescOnce sync.Once
	file_state_audio_proto_rawDescData []byte
)

func file_state_audio_proto_rawDescGZIP() []byte {
	file_state_audio_proto_rawDescOnce.Do(func() {
		file_state_audio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_audio_proto_rawDesc), len(file_state_audio_proto_rawDesc)))
	})
	return file_state_audio_proto_rawDescData
}

var file_state_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_state_audio_proto_goTypes = []any{
	(*AudioVolume)(nil), // 0: BSB_State.AudioVolume
}
var file_state_audio_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_state_audio_proto_init() }
func file_state_audio_proto_init() {
	if File_state_audio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_audio_proto_rawDesc), len(file_state_audio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_audio_proto_goTypes,
		DependencyIndexes: file_state_audio_proto_depIdxs,
		MessageInfos:      file_state_audio_proto_msgTypes,
	}.Build()
	File_state_audio_proto = out.File
	file_state_audio_proto_goTypes = nil
	file_state_audio_proto_depIdxs = nil
}
