// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: state/brightness.proto

package statepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BrightnessAutomatic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrightnessAutomatic) Reset() {
	*x = BrightnessAutomatic{}
	mi := &file_state_brightness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrightnessAutomatic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrightnessAutomatic) ProtoMessage() {}

func (x *BrightnessAutomatic) ProtoReflect() protoreflect.Message {
	mi := &file_state_brightness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrightnessAutomatic.ProtoReflect.Descriptor instead.
func (*BrightnessAutomatic) Descriptor() ([]byte, []int) {
	return file_state_brightness_proto_rawDescGZIP(), []int{0}
}

type BrightnessManual struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brightness    uint32                 `protobuf:"varint,1,opt,name=brightness,proto3" json:"brightness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrightnessManual) Reset() {
	*x = BrightnessManual{}
	mi := &file_state_brightness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrightnessManual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrightnessManual) ProtoMessage() {}

func (x *BrightnessManual) ProtoReflect() protoreflect.Message {
	mi := &file_state_brightness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrightnessManual.ProtoReflect.Descriptor instead.
func (*BrightnessManual) Descriptor() ([]byte, []int) {
	return file_state_brightness_proto_rawDescGZIP(), []int{1}
}

func (x *BrightnessManual) GetBrightness() uint32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

type Brightness struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Setting:
	//
	//	*Brightness_Automatic
	//	*Brightness_Manual
	Setting          isBrightness_Setting `protobuf_oneof:"setting"`
	ActualBrightness uint32               `protobuf:"varint,3,opt,name=actual_brightness,json=actualBrightness,proto3" json:"actual_brightness,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Brightness) Reset() {
	*x = Brightness{}
	mi := &file_state_brightness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Brightness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Brightness) ProtoMessage() {}

func (x *Brightness) ProtoReflect() protoreflect.Message {
	mi := &file_state_brightness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Brightness.ProtoReflect.Descriptor instead.
func (*Brightness) Descriptor() ([]byte, []int) {
	return file_state_brightness_proto_rawDescGZIP(), []int{2}
}

func (x *Brightness) GetSetting() isBrightness_Setting {
	if x != nil {
		return x.Setting
	}
	return nil
}

func (x *Brightness) GetAutomatic() *BrightnessAutomatic {
	if x != nil {
		if x, ok := x.Setting.(*Brightness_Automatic); ok {
			return x.Automatic
		}
	}
	return nil
}

func (x *Brightness) GetManual() *BrightnessManual {
	if x != nil {
		if x, ok := x.Setting.(*Brightness_Manual); ok {
			return x.Manual
		}
	}
	return nil
}

func (x *Brightness) GetActualBrightness() uint32 {
	if x != nil {
		return x.ActualBrightness
	}
	return 0
}

type isBrightness_Setting interface {
	isBrightness_Setting()
}

type Brightness_Automatic struct {
	Automatic *BrightnessAutomatic `protobuf:"bytes,1,opt,name=automatic,proto3,oneof"`
}

type Brightness_Manual struct {
	Manual *BrightnessManual `protobuf:"bytes,2,opt,name=manual,proto3,oneof"`
}

func (*Brightness_Automatic) isBrightness_Setting() {}

func (*Brightness_Manual) isBrightness_Setting() {}

var File_state_brightness_proto protoreflect.FileDescriptor

const file_state_brightness_proto_rawDesc = "" +
	"\n" +
	"\x16state/brightness.proto\x12\tBSB_State\"\x15\n" +
	"\x13BrightnessAutomatic\"2\n" +
	"\x10BrightnessManual\x12\x1e\n" +
	"\n" +
	"brightness\x18\x01 \x01(\rR\n" +
	"brightness\"\xbb\x01\n" +
	"\n" +
	"Brightness\x12>\n" +
	"\tautomatic\x18\x01 \x01(\v2\x1e.BSB_State.BrightnessAutomaticH\x00R\tautomatic\x125\n" +
	"\x06manual\x18\x02 \x01(\v2\x1b.BSB_State.BrightnessManualH\x00R\x06manual\x12+\n" +
	"\x11actual_brightness\x18\x03 \x01(\rR\x10actualBrightnessB\t\n" +
	"\asettingb\x06proto3"

var (
	file_state_brightness_proto_rawDescOnce sync.Once
	file_state_brightness_proto_rawDescData []byte
)

func file_state_brightness_proto_rawDescGZIP() []byte {
	file_state_brightness_proto_rawDescOnce.Do(func() {
		file_state_brightness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_brightness_proto_rawDesc), len(file_state_brightness_proto_rawDesc)))
	})
	return file_state_brightness_proto_rawDescData
}

var file_state_brightness_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_state_brightness_proto_goTypes = []any{
	(*BrightnessAutomatic)(nil), // 0: BSB_State.BrightnessAutomatic
	(*BrightnessManual)(nil),    // 1: BSB_State.BrightnessManual
	(*Brightness)(nil),          // 2: BSB_State.Brightness
}
var file_state_brightness_proto_depIdxs = []int32{
	0, // 0: BSB_State.Brightness.automatic:type_name -> BSB_State.BrightnessAutomatic
	1, // 1: BSB_State.Brightness.manual:type_name -> BSB_State.BrightnessManual
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_state_brightness_proto_init() }
func file_state_brightness_proto_init() {
	if File_state_brightness_proto != nil {
		return
	}
	file_state_brightness_proto_msgTypes[2].OneofWrappers = []any{
		(*Brightness_Automatic)(nil),
		(*Brightness_Manual)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_brightness_proto_rawDesc), len(file_state_brightness_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_brightness_proto_goTypes,
		DependencyIndexes: file_state_brightness_proto_depIdxs,
		MessageInfos:      file_state_brightness_proto_msgTypes,
	}.Build()
	File_state_brightness_proto = out.File
	file_state_brightness_proto_goTypes = nil
	file_state_brightness_proto_depIdxs = nil
}
