// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: state/matter.proto

package statepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatterCommissioningStatus int32

const (
	MatterCommissioningStatus_NEVER_STARTED          MatterCommissioningStatus = 0
	MatterCommissioningStatus_STARTED                MatterCommissioningStatus = 1
	MatterCommissioningStatus_COMPLETED_SUCCESSFULLY MatterCommissioningStatus = 2
	MatterCommissioningStatus_FAILED                 MatterCommissioningStatus = 3
)

// Enum value maps for MatterCommissioningStatus.
var (
	MatterCommissioningStatus_name = map[int32]string{
		0: "NEVER_STARTED",
		1: "STARTED",
		2: "COMPLETED_SUCCESSFULLY",
		3: "FAILED",
	}
	MatterCommissioningStatus_value = map[string]int32{
		"NEVER_STARTED":          0,
		"STARTED":                1,
		"COMPLETED_SUCCESSFULLY": 2,
		"FAILED":                 3,
	}
)

func (x MatterCommissioningStatus) Enum() *MatterCommissioningStatus {
	p := new(MatterCommissioningStatus)
	*p = x
	return p
}

func (x MatterCommissioningStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatterCommissioningStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_state_matter_proto_enumTypes[0].Descriptor()
}

func (MatterCommissioningStatus) Type() protoreflect.EnumType {
	return &file_state_matter_proto_enumTypes[0]
}

func (x MatterCommissioningStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatterCommissioningStatus.Descriptor instead.
func (MatterCommissioningStatus) EnumDescriptor() ([]byte, []int) {
	return file_state_matter_proto_rawDescGZIP(), []int{0}
}

type MatterCommissioningState struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        MatterCommissioningStatus `protobuf:"varint,1,opt,name=status,proto3,enum=BSB_State.MatterCommissioningStatus" json:"status,omitempty"`
	Timestamp     uint64                    `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatterCommissioningState) Reset() {
	*x = MatterCommissioningState{}
	mi := &file_state_matter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatterCommissioningState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatterCommissioningState) ProtoMessage() {}

func (x *MatterCommissioningState) ProtoReflect() protoreflect.Message {
	mi := &file_state_matter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatterCommissioningState.ProtoReflect.Descriptor instead.
func (*MatterCommissioningState) Descriptor() ([]byte, []int) {
	return file_state_matter_proto_rawDescGZIP(), []int{0}
}

func (x *MatterCommissioningState) GetStatus() MatterCommissioningStatus {
	if x != nil {
		return x.Status
	}
	return MatterCommissioningStatus_NEVER_STARTED
}

func (x *MatterCommissioningState) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Matter struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	FabricCount   uint32                    `protobuf:"varint,1,opt,name=fabric_count,json=fabricCount,proto3" json:"fabric_count,omitempty"`
	State         *MatterCommissioningState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matter) Reset() {
	*x = Matter{}
	mi := &file_state_matter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matter) ProtoMessage() {}

func (x *Matter) ProtoReflect() protoreflect.Message {
	mi := &file_state_matter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matter.ProtoReflect.Descriptor instead.
func (*Matter) Descriptor() ([]byte, []int) {
	return file_state_matter_proto_rawDescGZIP(), []int{1}
}

func (x *Matter) GetFabricCount() uint32 {
	if x != nil {
		return x.FabricCount
	}
	return 0
}

func (x *Matter) GetState() *MatterCommissioningState {
	if x != nil {
		return x.State
	}
	return nil
}

var File_state_matter_proto protoreflect.FileDescriptor

const file_state_matter_proto_rawDesc = "" +
	"\n" +
	"\x12state/matter.proto\x12\tBSB_State\"v\n" +
	"\x18MatterCommissioningState\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2$.BSB_State.MatterCommissioningStatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x06R\ttimestamp\"f\n" +
	"\x06Matter\x12!\n" +
	"\ffabric_count\x18\x01 \x01(\rR\vfabricCount\x129\n" +
	"\x05state\x18\x02 \x01(\v2#.BSB_State.MatterCommissioningStateR\x05state*c\n" +
	"\x19MatterCommissioningStatus\x12\x11\n" +
	"\rNEVER_STARTED\x10\x00\x12\v\n" +
	"\aSTARTED\x10\x01\x12\x1a\n" +
	"\x16COMPLETED_SUCCESSFULLY\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03b\x06proto3"

var (
	file_state_matter_proto_rawDescOnce sync.Once
	file_state_matter_proto_rawDescData []byte
)

func file_state_matter_proto_rawDescGZIP() []byte {
	file_state_matter_proto_rawDescOnce.Do(func() {
		file_state_matter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_matter_proto_rawDesc), len(file_state_matter_proto_rawDesc)))
	})
	return file_state_matter_proto_rawDescData
}

var file_state_matter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_state_matter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_state_matter_proto_goTypes = []any{
	(MatterCommissioningStatus)(0),   // 0: BSB_State.MatterCommissioningStatus
	(*MatterCommissioningState)(nil), // 1: BSB_State.MatterCommissioningState
	(*Matter)(nil),                   // 2: BSB_State.Matter
}
var file_state_matter_proto_depIdxs = []int32{
	0, // 0: BSB_State.MatterCommissioningState.status:type_name -> BSB_State.MatterCommissioningStatus
	1, // 1: BSB_State.Matter.state:type_name -> BSB_State.MatterCommissioningState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_state_matter_proto_init() }
func file_state_matter_proto_init() {
	if File_state_matter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_matter_proto_rawDesc), len(file_state_matter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_matter_proto_goTypes,
		DependencyIndexes: file_state_matter_proto_depIdxs,
		EnumInfos:         file_state_matter_proto_enumTypes,
		MessageInfos:      file_state_matter_proto_msgTypes,
	}.Build()
	File_state_matter_proto = out.File
	file_state_matter_proto_goTypes = nil
	file_state_matter_proto_depIdxs = nil
}
