// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: state/power.proto

package statepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatteryStatus int32

const (
	BatteryStatus_DISCHARGING BatteryStatus = 0
	BatteryStatus_CHARGING    BatteryStatus = 1
	BatteryStatus_CHARGED     BatteryStatus = 2
)

// Enum value maps for BatteryStatus.
var (
	BatteryStatus_name = map[int32]string{
		0: "DISCHARGING",
		1: "CHARGING",
		2: "CHARGED",
	}
	BatteryStatus_value = map[string]int32{
		"DISCHARGING": 0,
		"CHARGING":    1,
		"CHARGED":     2,
	}
)

func (x BatteryStatus) Enum() *BatteryStatus {
	p := new(BatteryStatus)
	*p = x
	return p
}

func (x BatteryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BatteryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_state_power_proto_enumTypes[0].Descriptor()
}

func (BatteryStatus) Type() protoreflect.EnumType {
	return &file_state_power_proto_enumTypes[0]
}

func (x BatteryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BatteryStatus.Descriptor instead.
func (BatteryStatus) EnumDescriptor() ([]byte, []int) {
	return file_state_power_proto_rawDescGZIP(), []int{0}
}

type UnknownPowerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnknownPowerState) Reset() {
	*x = UnknownPowerState{}
	mi := &file_state_power_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnknownPowerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnknownPowerState) ProtoMessage() {}

func (x *UnknownPowerState) ProtoReflect() protoreflect.Message {
	mi := &file_state_power_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnknownPowerState.ProtoReflect.Descriptor instead.
func (*UnknownPowerState) Descriptor() ([]byte, []int) {
	return file_state_power_proto_rawDescGZIP(), []int{0}
}

type PowerState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BatteryStatus        BatteryStatus          `protobuf:"varint,1,opt,name=battery_status,json=batteryStatus,proto3,enum=BSB_State.BatteryStatus" json:"battery_status,omitempty"`
	BatteryChargePercent uint32                 `protobuf:"varint,2,opt,name=battery_charge_percent,json=batteryChargePercent,proto3" json:"battery_charge_percent,omitempty"`
	BatteryVoltageMv     uint32                 `protobuf:"varint,3,opt,name=battery_voltage_mv,json=batteryVoltageMv,proto3" json:"battery_voltage_mv,omitempty"`
	BatteryCurrentMa     int32                  `protobuf:"zigzag32,4,opt,name=battery_current_ma,json=batteryCurrentMa,proto3" json:"battery_current_ma,omitempty"`
	UsbVoltageMv         uint32                 `protobuf:"varint,5,opt,name=usb_voltage_mv,json=usbVoltageMv,proto3" json:"usb_voltage_mv,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PowerState) Reset() {
	*x = PowerState{}
	mi := &file_state_power_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerState) ProtoMessage() {}

func (x *PowerState) ProtoReflect() protoreflect.Message {
	mi := &file_state_power_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerState.ProtoReflect.Descriptor instead.
func (*PowerState) Descriptor() ([]byte, []int) {
	return file_state_power_proto_rawDescGZIP(), []int{1}
}

func (x *PowerState) GetBatteryStatus() BatteryStatus {
	if x != nil {
		return x.BatteryStatus
	}
	return BatteryStatus_DISCHARGING
}

func (x *PowerState) GetBatteryChargePercent() uint32 {
	if x != nil {
		return x.BatteryChargePercent
	}
	return 0
}

func (x *PowerState) GetBatteryVoltageMv() uint32 {
	if x != nil {
		return x.BatteryVoltageMv
	}
	return 0
}

func (x *PowerState) GetBatteryCurrentMa() int32 {
	if x != nil {
		return x.BatteryCurrentMa
	}
	return 0
}

func (x *PowerState) GetUsbVoltageMv() uint32 {
	if x != nil {
		return x.UsbVoltageMv
	}
	return 0
}

type Power struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to State:
	//
	//	*Power_Unknown
	//	*Power_Known
	State         isPower_State `protobuf_oneof:"state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Power) Reset() {
	*x = Power{}
	mi := &file_state_power_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Power) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Power) ProtoMessage() {}

func (x *Power) ProtoReflect() protoreflect.Message {
	mi := &file_state_power_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Power.ProtoReflect.Descriptor instead.
func (*Power) Descriptor() ([]byte, []int) {
	return file_state_power_proto_rawDescGZIP(), []int{2}
}

func (x *Power) GetState() isPower_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Power) GetUnknown() *UnknownPowerState {
	if x != nil {
		if x, ok := x.State.(*Power_Unknown); ok {
			return x.Unknown
		}
	}
	return nil
}

func (x *Power) GetKnown() *PowerState {
	if x != nil {
		if x, ok := x.State.(*Power_Known); ok {
			return x.Known
		}
	}
	return nil
}

type isPower_State interface {
	isPower_State()
}

type Power_Unknown struct {
	Unknown *UnknownPowerState `protobuf:"bytes,1,opt,name=unknown,proto3,oneof"`
}

type Power_Known struct {
	Known *PowerState `protobuf:"bytes,2,opt,name=known,proto3,oneof"`
}

func (*Power_Unknown) isPower_State() {}

func (*Power_Known) isPower_State() {}

var File_state_power_proto protoreflect.FileDescriptor

const file_state_power_proto_rawDesc = "" +
	"\n" +
	"\x11state/power.proto\x12\tBSB_State\"\x13\n" +
	"\x11UnknownPowerState\"\x85\x02\n" +
	"\n" +
	"PowerState\x12?\n" +
	"\x0ebattery_status\x18\x01 \x01(\x0e2\x18.BSB_State.BatteryStatusR\rbatteryStatus\x124\n" +
	"\x16battery_charge_percent\x18\x02 \x01(\rR\x14batteryChargePercent\x12,\n" +
	"\x12battery_voltage_mv\x18\x03 \x01(\rR\x10batteryVoltageMv\x12,\n" +
	"\x12battery_current_ma\x18\x04 \x01(\x11R\x10batteryCurrentMa\x12$\n" +
	"\x0eusb_voltage_mv\x18\x05 \x01(\rR\fusbVoltageMv\"y\n" +
	"\x05Power\x128\n" +
	"\aunknown\x18\x01 \x01(\v2\x1c.BSB_State.UnknownPowerStateH\x00R\aunknown\x12-\n" +
	"\x05known\x18\x02 \x01(\v2\x15.BSB_State.PowerStateH\x00R\x05knownB\a\n" +
	"\x05state*;\n" +
	"\rBatteryStatus\x12\x0f\n" +
	"\vDISCHARGING\x10\x00\x12\f\n" +
	"\bCHARGING\x10\x01\x12\v\n" +
	"\aCHARGED\x10\x02b\x06proto3"

var (
	file_state_power_proto_rawDescOnce sync.Once
	file_state_power_proto_rawDescData []byte
)

func file_state_power_proto_rawDescGZIP() []byte {
	file_state_power_proto_rawDescOnce.Do(func() {
		file_state_power_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_power_proto_rawDesc), len(file_state_power_proto_rawDesc)))
	})
	return file_state_power_proto_rawDescData
}

var file_state_power_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_state_power_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_state_power_proto_goTypes = []any{
	(BatteryStatus)(0),        // 0: BSB_State.BatteryStatus
	(*UnknownPowerState)(nil), // 1: BSB_State.UnknownPowerState
	(*PowerState)(nil),        // 2: BSB_State.PowerState
	(*Power)(nil),             // 3: BSB_State.Power
}
var file_state_power_proto_depIdxs = []int32{
	0, // 0: BSB_State.PowerState.battery_status:type_name -> BSB_State.BatteryStatus
	1, // 1: BSB_State.Power.unknown:type_name -> BSB_State.UnknownPowerState
	2, // 2: BSB_State.Power.known:type_name -> BSB_State.PowerState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_state_power_proto_init() }
func file_state_power_proto_init() {
	if File_state_power_proto != nil {
		return
	}
	file_state_power_proto_msgTypes[2].OneofWrappers = []any{
		(*Power_Unknown)(nil),
		(*Power_Known)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_power_proto_rawDesc), len(file_state_power_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_power_proto_goTypes,
		DependencyIndexes: file_state_power_proto_depIdxs,
		EnumInfos:         file_state_power_proto_enumTypes,
		MessageInfos:      file_state_power_proto_msgTypes,
	}.Build()
	File_state_power_proto = out.File
	file_state_power_proto_goTypes = nil
	file_state_power_proto_depIdxs = nil
}
