// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: state.proto

package statepb

import (
	blepb "github.com/lxdb/busylib-go/proto/blepb"
	errorpb "github.com/lxdb/busylib-go/proto/errorpb"
	framepb "github.com/lxdb/busylib-go/proto/framepb"
	inputpb "github.com/lxdb/busylib-go/proto/inputpb"
	timerpb "github.com/lxdb/busylib-go/proto/timerpb"
	updatepb "github.com/lxdb/busylib-go/proto/updatepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to State:
	//
	//	*StateUpdate_DeviceName
	//	*StateUpdate_Power
	//	*StateUpdate_Brightness
	//	*StateUpdate_AudioVolume
	//	*StateUpdate_Wifi
	//	*StateUpdate_UpdateState
	//	*StateUpdate_UpdateCheck
	//	*StateUpdate_Timezone
	//	*StateUpdate_Matter
	//	*StateUpdate_Frame
	//	*StateUpdate_Input
	//	*StateUpdate_Timer
	//	*StateUpdate_Ble
	//	*StateUpdate_AutoUpdateState
	//	*StateUpdate_TimerProfiles
	State         isStateUpdate_State `protobuf_oneof:"state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateUpdate) Reset() {
	*x = StateUpdate{}
	mi := &file_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdate) ProtoMessage() {}

func (x *StateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdate.ProtoReflect.Descriptor instead.
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *StateUpdate) GetState() isStateUpdate_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *StateUpdate) GetDeviceName() *DeviceName {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_DeviceName); ok {
			return x.DeviceName
		}
	}
	return nil
}

func (x *StateUpdate) GetPower() *Power {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_Power); ok {
			return x.Power
		}
	}
	return nil
}

func (x *StateUpdate) GetBrightness() *Brightness {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_Brightness); ok {
			return x.Brightness
		}
	}
	return nil
}

func (x *StateUpdate) GetAudioVolume() *AudioVolume {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_AudioVolume); ok {
			return x.AudioVolume
		}
	}
	return nil
}

func (x *StateUpdate) GetWifi() *Wifi {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_Wifi); ok {
			return x.Wifi
		}
	}
	return nil
}

func (x *StateUpdate) GetUpdateState() *updatepb.UpdateState {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_UpdateState); ok {
			return x.UpdateState
		}
	}
	return nil
}

func (x *StateUpdate) GetUpdateCheck() *updatepb.CheckState {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_UpdateCheck); ok {
			return x.UpdateCheck
		}
	}
	return nil
}

func (x *StateUpdate) GetTimezone() *Timezone {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_Timezone); ok {
			return x.Timezone
		}
	}
	return nil
}

func (x *StateUpdate) GetMatter() *Matter {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_Matter); ok {
			return x.Matter
		}
	}
	return nil
}

func (x *StateUpdate) GetFrame() *framepb.Frame {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

func (x *StateUpdate) GetInput() *inputpb.InputEvent {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *StateUpdate) GetTimer() *timerpb.Timer {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_Timer); ok {
			return x.Timer
		}
	}
	return nil
}

func (x *StateUpdate) GetBle() *blepb.Ble {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_Ble); ok {
			return x.Ble
		}
	}
	return nil
}

func (x *StateUpdate) GetAutoUpdateState() *updatepb.AutoUpdateState {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_AutoUpdateState); ok {
			return x.AutoUpdateState
		}
	}
	return nil
}

func (x *StateUpdate) GetTimerProfiles() *timerpb.Profiles {
	if x != nil {
		if x, ok := x.State.(*StateUpdate_TimerProfiles); ok {
			return x.TimerProfiles
		}
	}
	return nil
}

type isStateUpdate_State interface {
	isStateUpdate_State()
}

type StateUpdate_DeviceName struct {
	DeviceName *DeviceName `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3,oneof"`
}

type StateUpdate_Power struct {
	Power *Power `protobuf:"bytes,2,opt,name=power,proto3,oneof"`
}

type StateUpdate_Brightness struct {
	Brightness *Brightness `protobuf:"bytes,3,opt,name=brightness,proto3,oneof"`
}

type StateUpdate_AudioVolume struct {
	AudioVolume *AudioVolume `protobuf:"bytes,4,opt,name=audio_volume,json=audioVolume,proto3,oneof"`
}

type StateUpdate_Wifi struct {
	Wifi *Wifi `protobuf:"bytes,5,opt,name=wifi,proto3,oneof"`
}

type StateUpdate_UpdateState struct {
	UpdateState *updatepb.UpdateState `protobuf:"bytes,6,opt,name=update_state,json=updateState,proto3,oneof"`
}

type StateUpdate_UpdateCheck struct {
	UpdateCheck *updatepb.CheckState `protobuf:"bytes,7,opt,name=update_check,json=updateCheck,proto3,oneof"`
}

type StateUpdate_Timezone struct {
	Timezone *Timezone `protobuf:"bytes,8,opt,name=timezone,proto3,oneof"`
}

type StateUpdate_Matter struct {
	Matter *Matter `protobuf:"bytes,9,opt,name=matter,proto3,oneof"`
}

type StateUpdate_Frame struct {
	Frame *framepb.Frame `protobuf:"bytes,10,opt,name=frame,proto3,oneof"`
}

type StateUpdate_Input struct {
	Input *inputpb.InputEvent `protobuf:"bytes,11,opt,name=input,proto3,oneof"`
}

type StateUpdate_Timer struct {
	Timer *timerpb.Timer `protobuf:"bytes,12,opt,name=timer,proto3,oneof"`
}

type StateUpdate_Ble struct {
	Ble *blepb.Ble `protobuf:"bytes,13,opt,name=ble,proto3,oneof"`
}

type StateUpdate_AutoUpdateState struct {
	AutoUpdateState *updatepb.AutoUpdateState `protobuf:"bytes,14,opt,name=auto_update_state,json=autoUpdateState,proto3,oneof"`
}

type StateUpdate_TimerProfiles struct {
	TimerProfiles *timerpb.Profiles `protobuf:"bytes,15,opt,name=timer_profiles,json=timerProfiles,proto3,oneof"`
}

func (*StateUpdate_DeviceName) isStateUpdate_State() {}

func (*StateUpdate_Power) isStateUpdate_State() {}

func (*StateUpdate_Brightness) isStateUpdate_State() {}

func (*StateUpdate_AudioVolume) isStateUpdate_State() {}

func (*StateUpdate_Wifi) isStateUpdate_State() {}

func (*StateUpdate_UpdateState) isStateUpdate_State() {}

func (*StateUpdate_UpdateCheck) isStateUpdate_State() {}

func (*StateUpdate_Timezone) isStateUpdate_State() {}

func (*StateUpdate_Matter) isStateUpdate_State() {}

func (*StateUpdate_Frame) isStateUpdate_State() {}

func (*StateUpdate_Input) isStateUpdate_State() {}

func (*StateUpdate_Timer) isStateUpdate_State() {}

func (*StateUpdate_Ble) isStateUpdate_State() {}

func (*StateUpdate_AutoUpdateState) isStateUpdate_State() {}

func (*StateUpdate_TimerProfiles) isStateUpdate_State() {}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Updates       []*StateUpdate         `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	Error         *errorpb.Error         `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

func (x *State) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *State) GetUpdates() []*StateUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *State) GetError() *errorpb.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_state_proto protoreflect.FileDescriptor

const file_state_proto_rawDesc = "" +
	"\n" +
	"\vstate.proto\x12\tBSB_State\x1a\x17state/device_name.proto\x1a\x16state/brightness.proto\x1a\x11state/power.proto\x1a\x11state/audio.proto\x1a\x10state/wifi.proto\x1a\x12state/update.proto\x1a\x14state/timezone.proto\x1a\x12state/matter.proto\x1a\x0fstate/ble.proto\x1a\vframe.proto\x1a\vtimer.proto\x1a\vinput.proto\x1a\verror.proto\"\xa6\x06\n" +
	"\vStateUpdate\x128\n" +
	"\vdevice_name\x18\x01 \x01(\v2\x15.BSB_State.DeviceNameH\x00R\n" +
	"deviceName\x12(\n" +
	"\x05power\x18\x02 \x01(\v2\x10.BSB_State.PowerH\x00R\x05power\x127\n" +
	"\n" +
	"brightness\x18\x03 \x01(\v2\x15.BSB_State.BrightnessH\x00R\n" +
	"brightness\x12;\n" +
	"\faudio_volume\x18\x04 \x01(\v2\x16.BSB_State.AudioVolumeH\x00R\vaudioVolume\x12%\n" +
	"\x04wifi\x18\x05 \x01(\v2\x0f.BSB_State.WifiH\x00R\x04wifi\x12<\n" +
	"\fupdate_state\x18\x06 \x01(\v2\x17.BSB_Update.UpdateStateH\x00R\vupdateState\x12;\n" +
	"\fupdate_check\x18\a \x01(\v2\x16.BSB_Update.CheckStateH\x00R\vupdateCheck\x121\n" +
	"\btimezone\x18\b \x01(\v2\x13.BSB_State.TimezoneH\x00R\btimezone\x12+\n" +
	"\x06matter\x18\t \x01(\v2\x11.BSB_State.MatterH\x00R\x06matter\x12(\n" +
	"\x05frame\x18\n" +
	" \x01(\v2\x10.BSB_Frame.FrameH\x00R\x05frame\x12-\n" +
	"\x05input\x18\v \x01(\v2\x15.BSB_Input.InputEventH\x00R\x05input\x12(\n" +
	"\x05timer\x18\f \x01(\v2\x10.BSB_Timer.TimerH\x00R\x05timer\x12&\n" +
	"\x03ble\x18\r \x01(\v2\x12.BSB_State.Ble.BleH\x00R\x03ble\x12I\n" +
	"\x11auto_update_state\x18\x0e \x01(\v2\x1b.BSB_Update.AutoUpdateStateH\x00R\x0fautoUpdateState\x12<\n" +
	"\x0etimer_profiles\x18\x0f \x01(\v2\x13.BSB_Timer.ProfilesH\x00R\rtimerProfilesB\a\n" +
	"\x05state\"\x8e\x01\n" +
	"\x05State\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x06R\ttimestamp\x120\n" +
	"\aupdates\x18\x02 \x03(\v2\x16.BSB_State.StateUpdateR\aupdates\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x10.BSB_Error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_errorb\x06proto3"

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData []byte
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)))
	})
	return file_state_proto_rawDescData
}

var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_state_proto_goTypes = []any{
	(*StateUpdate)(nil),              // 0: BSB_State.StateUpdate
	(*State)(nil),                    // 1: BSB_State.State
	(*DeviceName)(nil),               // 2: BSB_State.DeviceName
	(*Power)(nil),                    // 3: BSB_State.Power
	(*Brightness)(nil),               // 4: BSB_State.Brightness
	(*AudioVolume)(nil),              // 5: BSB_State.AudioVolume
	(*Wifi)(nil),                     // 6: BSB_State.Wifi
	(*updatepb.UpdateState)(nil),     // 7: BSB_Update.UpdateState
	(*updatepb.CheckState)(nil),      // 8: BSB_Update.CheckState
	(*Timezone)(nil),                 // 9: BSB_State.Timezone
	(*Matter)(nil),                   // 10: BSB_State.Matter
	(*framepb.Frame)(nil),            // 11: BSB_Frame.Frame
	(*inputpb.InputEvent)(nil),       // 12: BSB_Input.InputEvent
	(*timerpb.Timer)(nil),            // 13: BSB_Timer.Timer
	(*blepb.Ble)(nil),                // 14: BSB_State.Ble.Ble
	(*updatepb.AutoUpdateState)(nil), // 15: BSB_Update.AutoUpdateState
	(*timerpb.Profiles)(nil),         // 16: BSB_Timer.Profiles
	(*errorpb.Error)(nil),            // 17: BSB_Error.Error
}
var file_state_proto_depIdxs = []int32{
	2,  // 0: BSB_State.StateUpdate.device_name:type_name -> BSB_State.DeviceName
	3,  // 1: BSB_State.StateUpdate.power:type_name -> BSB_State.Power
	4,  // 2: BSB_State.StateUpdate.brightness:type_name -> BSB_State.Brightness
	5,  // 3: BSB_State.StateUpdate.audio_volume:type_name -> BSB_State.AudioVolume
	6,  // 4: BSB_State.StateUpdate.wifi:type_name -> BSB_State.Wifi
	7,  // 5: BSB_State.StateUpdate.update_state:type_name -> BSB_Update.UpdateState
	8,  // 6: BSB_State.StateUpdate.update_check:type_name -> BSB_Update.CheckState
	9,  // 7: BSB_State.StateUpdate.timezone:type_name -> BSB_State.Timezone
	10, // 8: BSB_State.StateUpdate.matter:type_name -> BSB_State.Matter
	11, // 9: BSB_State.StateUpdate.frame:type_name -> BSB_Frame.Frame
	12, // 10: BSB_State.StateUpdate.input:type_name -> BSB_Input.InputEvent
	13, // 11: BSB_State.StateUpdate.timer:type_name -> BSB_Timer.Timer
	14, // 12: BSB_State.StateUpdate.ble:type_name -> BSB_State.Ble.Ble
	15, // 13: BSB_State.StateUpdate.auto_update_state:type_name -> BSB_Update.AutoUpdateState
	16, // 14: BSB_State.StateUpdate.timer_profiles:type_name -> BSB_Timer.Profiles
	0,  // 15: BSB_State.State.updates:type_name -> BSB_State.StateUpdate
	17, // 16: BSB_State.State.error:type_name -> BSB_Error.Error
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	file_state_device_name_proto_init()
	file_state_brightness_proto_init()
	file_state_power_proto_init()
	file_state_audio_proto_init()
	file_state_wifi_proto_init()
	file_state_timezone_proto_init()
	file_state_matter_proto_init()
	file_state_proto_msgTypes[0].OneofWrappers = []any{
		(*StateUpdate_DeviceName)(nil),
		(*StateUpdate_Power)(nil),
		(*StateUpdate_Brightness)(nil),
		(*StateUpdate_AudioVolume)(nil),
		(*StateUpdate_Wifi)(nil),
		(*StateUpdate_UpdateState)(nil),
		(*StateUpdate_UpdateCheck)(nil),
		(*StateUpdate_Timezone)(nil),
		(*StateUpdate_Matter)(nil),
		(*StateUpdate_Frame)(nil),
		(*StateUpdate_Input)(nil),
		(*StateUpdate_Timer)(nil),
		(*StateUpdate_Ble)(nil),
		(*StateUpdate_AutoUpdateState)(nil),
		(*StateUpdate_TimerProfiles)(nil),
	}
	file_state_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
