// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: state/timezone.proto

package statepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Timezone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`        // Timezone name
	Offset        int32                  `protobuf:"zigzag32,2,opt,name=offset,proto3" json:"offset,omitempty"` // Offset from UTC in minutes
	Abbr          string                 `protobuf:"bytes,3,opt,name=abbr,proto3" json:"abbr,omitempty"`        // Timezone abbreviation (e.g. CEST)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timezone) Reset() {
	*x = Timezone{}
	mi := &file_state_timezone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timezone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timezone) ProtoMessage() {}

func (x *Timezone) ProtoReflect() protoreflect.Message {
	mi := &file_state_timezone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timezone.ProtoReflect.Descriptor instead.
func (*Timezone) Descriptor() ([]byte, []int) {
	return file_state_timezone_proto_rawDescGZIP(), []int{0}
}

func (x *Timezone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Timezone) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Timezone) GetAbbr() string {
	if x != nil {
		return x.Abbr
	}
	return ""
}

var File_state_timezone_proto protoreflect.FileDescriptor

const file_state_timezone_proto_rawDesc = "" +
	"\n" +
	"\x14state/timezone.proto\x12\tBSB_State\"J\n" +
	"\bTimezone\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x11R\x06offset\x12\x12\n" +
	"\x04abbr\x18\x03 \x01(\tR\x04abbrb\x06proto3"

var (
	file_state_timezone_proto_rawDescOnce sync.Once
	file_state_timezone_proto_rawDescData []byte
)

func file_state_timezone_proto_rawDescGZIP() []byte {
	file_state_timezone_proto_rawDescOnce.Do(func() {
		file_state_timezone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_timezone_proto_rawDesc), len(file_state_timezone_proto_rawDesc)))
	})
	return file_state_timezone_proto_rawDescData
}

var file_state_timezone_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_state_timezone_proto_goTypes = []any{
	(*Timezone)(nil), // 0: BSB_State.Timezone
}
var file_state_timezone_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_state_timezone_proto_init() }
func file_state_timezone_proto_init() {
	if File_state_timezone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_timezone_proto_rawDesc), len(file_state_timezone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_timezone_proto_goTypes,
		DependencyIndexes: file_state_timezone_proto_depIdxs,
		MessageInfos:      file_state_timezone_proto_msgTypes,
	}.Build()
	File_state_timezone_proto = out.File
	file_state_timezone_proto_goTypes = nil
	file_state_timezone_proto_depIdxs = nil
}
