// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: state/wifi.proto

package statepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WifiConnectionStatus int32

const (
	WifiConnectionStatus_CONNECTED     WifiConnectionStatus = 0
	WifiConnectionStatus_CONNECTING    WifiConnectionStatus = 1
	WifiConnectionStatus_DISCONNECTING WifiConnectionStatus = 2
	WifiConnectionStatus_RECONNECTING  WifiConnectionStatus = 3
)

// Enum value maps for WifiConnectionStatus.
var (
	WifiConnectionStatus_name = map[int32]string{
		0: "CONNECTED",
		1: "CONNECTING",
		2: "DISCONNECTING",
		3: "RECONNECTING",
	}
	WifiConnectionStatus_value = map[string]int32{
		"CONNECTED":     0,
		"CONNECTING":    1,
		"DISCONNECTING": 2,
		"RECONNECTING":  3,
	}
)

func (x WifiConnectionStatus) Enum() *WifiConnectionStatus {
	p := new(WifiConnectionStatus)
	*p = x
	return p
}

func (x WifiConnectionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiConnectionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_state_wifi_proto_enumTypes[0].Descriptor()
}

func (WifiConnectionStatus) Type() protoreflect.EnumType {
	return &file_state_wifi_proto_enumTypes[0]
}

func (x WifiConnectionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiConnectionStatus.Descriptor instead.
func (WifiConnectionStatus) EnumDescriptor() ([]byte, []int) {
	return file_state_wifi_proto_rawDescGZIP(), []int{0}
}

type WifiSecurity int32

const (
	WifiSecurity_UNKNOWN   WifiSecurity = 0
	WifiSecurity_OPEN      WifiSecurity = 1
	WifiSecurity_WPA       WifiSecurity = 2
	WifiSecurity_WPA2      WifiSecurity = 3
	WifiSecurity_WEP       WifiSecurity = 4
	WifiSecurity_WPA_WPA2  WifiSecurity = 5
	WifiSecurity_WPA3      WifiSecurity = 6
	WifiSecurity_WPA2_WPA3 WifiSecurity = 7
)

// Enum value maps for WifiSecurity.
var (
	WifiSecurity_name = map[int32]string{
		0: "UNKNOWN",
		1: "OPEN",
		2: "WPA",
		3: "WPA2",
		4: "WEP",
		5: "WPA_WPA2",
		6: "WPA3",
		7: "WPA2_WPA3",
	}
	WifiSecurity_value = map[string]int32{
		"UNKNOWN":   0,
		"OPEN":      1,
		"WPA":       2,
		"WPA2":      3,
		"WEP":       4,
		"WPA_WPA2":  5,
		"WPA3":      6,
		"WPA2_WPA3": 7,
	}
)

func (x WifiSecurity) Enum() *WifiSecurity {
	p := new(WifiSecurity)
	*p = x
	return p
}

func (x WifiSecurity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiSecurity) Descriptor() protoreflect.EnumDescriptor {
	return file_state_wifi_proto_enumTypes[1].Descriptor()
}

func (WifiSecurity) Type() protoreflect.EnumType {
	return &file_state_wifi_proto_enumTypes[1]
}

func (x WifiSecurity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiSecurity.Descriptor instead.
func (WifiSecurity) EnumDescriptor() ([]byte, []int) {
	return file_state_wifi_proto_rawDescGZIP(), []int{1}
}

type IpConfigurationMethod int32

const (
	IpConfigurationMethod_DHCP   IpConfigurationMethod = 0
	IpConfigurationMethod_STATIC IpConfigurationMethod = 1
)

// Enum value maps for IpConfigurationMethod.
var (
	IpConfigurationMethod_name = map[int32]string{
		0: "DHCP",
		1: "STATIC",
	}
	IpConfigurationMethod_value = map[string]int32{
		"DHCP":   0,
		"STATIC": 1,
	}
)

func (x IpConfigurationMethod) Enum() *IpConfigurationMethod {
	p := new(IpConfigurationMethod)
	*p = x
	return p
}

func (x IpConfigurationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpConfigurationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_state_wifi_proto_enumTypes[2].Descriptor()
}

func (IpConfigurationMethod) Type() protoreflect.EnumType {
	return &file_state_wifi_proto_enumTypes[2]
}

func (x IpConfigurationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpConfigurationMethod.Descriptor instead.
func (IpConfigurationMethod) EnumDescriptor() ([]byte, []int) {
	return file_state_wifi_proto_rawDescGZIP(), []int{2}
}

type IpProtocol int32

const (
	IpProtocol_IPV4 IpProtocol = 0
	IpProtocol_IPV6 IpProtocol = 1
)

// Enum value maps for IpProtocol.
var (
	IpProtocol_name = map[int32]string{
		0: "IPV4",
		1: "IPV6",
	}
	IpProtocol_value = map[string]int32{
		"IPV4": 0,
		"IPV6": 1,
	}
)

func (x IpProtocol) Enum() *IpProtocol {
	p := new(IpProtocol)
	*p = x
	return p
}

func (x IpProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_state_wifi_proto_enumTypes[3].Descriptor()
}

func (IpProtocol) Type() protoreflect.EnumType {
	return &file_state_wifi_proto_enumTypes[3]
}

func (x IpProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpProtocol.Descriptor instead.
func (IpProtocol) EnumDescriptor() ([]byte, []int) {
	return file_state_wifi_proto_rawDescGZIP(), []int{3}
}

type WifiStateUnknown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WifiStateUnknown) Reset() {
	*x = WifiStateUnknown{}
	mi := &file_state_wifi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiStateUnknown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiStateUnknown) ProtoMessage() {}

func (x *WifiStateUnknown) ProtoReflect() protoreflect.Message {
	mi := &file_state_wifi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiStateUnknown.ProtoReflect.Descriptor instead.
func (*WifiStateUnknown) Descriptor() ([]byte, []int) {
	return file_state_wifi_proto_rawDescGZIP(), []int{0}
}

type WifiStateInactive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WifiStateInactive) Reset() {
	*x = WifiStateInactive{}
	mi := &file_state_wifi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiStateInactive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiStateInactive) ProtoMessage() {}

func (x *WifiStateInactive) ProtoReflect() protoreflect.Message {
	mi := &file_state_wifi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiStateInactive.ProtoReflect.Descriptor instead.
func (*WifiStateInactive) Descriptor() ([]byte, []int) {
	return file_state_wifi_proto_rawDescGZIP(), []int{1}
}

type WifiStateActive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WifiConnectionStatus   `protobuf:"varint,1,opt,name=status,proto3,enum=BSB_State.WifiConnectionStatus" json:"status,omitempty"`
	Ssid          string                 `protobuf:"bytes,2,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Bssid         string                 `protobuf:"bytes,3,opt,name=bssid,proto3" json:"bssid,omitempty"`
	Channel       uint32                 `protobuf:"varint,4,opt,name=channel,proto3" json:"channel,omitempty"`
	Rssi          int32                  `protobuf:"zigzag32,5,opt,name=rssi,proto3" json:"rssi,omitempty"`
	Security      WifiSecurity           `protobuf:"varint,6,opt,name=security,proto3,enum=BSB_State.WifiSecurity" json:"security,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WifiStateActive) Reset() {
	*x = WifiStateActive{}
	mi := &file_state_wifi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiStateActive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiStateActive) ProtoMessage() {}

func (x *WifiStateActive) ProtoReflect() protoreflect.Message {
	mi := &file_state_wifi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiStateActive.ProtoReflect.Descriptor instead.
func (*WifiStateActive) Descriptor() ([]byte, []int) {
	return file_state_wifi_proto_rawDescGZIP(), []int{2}
}

func (x *WifiStateActive) GetStatus() WifiConnectionStatus {
	if x != nil {
		return x.Status
	}
	return WifiConnectionStatus_CONNECTED
}

func (x *WifiStateActive) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *WifiStateActive) GetBssid() string {
	if x != nil {
		return x.Bssid
	}
	return ""
}

func (x *WifiStateActive) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *WifiStateActive) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *WifiStateActive) GetSecurity() WifiSecurity {
	if x != nil {
		return x.Security
	}
	return WifiSecurity_UNKNOWN
}

type IpAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      IpProtocol             `protobuf:"varint,1,opt,name=protocol,proto3,enum=BSB_State.IpProtocol" json:"protocol,omitempty"`
	Method        IpConfigurationMethod  `protobuf:"varint,2,opt,name=method,proto3,enum=BSB_State.IpConfigurationMethod" json:"method,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Gateway       string                 `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Netmask       string                 `protobuf:"bytes,5,opt,name=netmask,proto3" json:"netmask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpAddress) Reset() {
	*x = IpAddress{}
	mi := &file_state_wifi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpAddress) ProtoMessage() {}

func (x *IpAddress) ProtoReflect() protoreflect.Message {
	mi := &file_state_wifi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpAddress.ProtoReflect.Descriptor instead.
func (*IpAddress) Descriptor() ([]byte, []int) {
	return file_state_wifi_proto_rawDescGZIP(), []int{3}
}

func (x *IpAddress) GetProtocol() IpProtocol {
	if x != nil {
		return x.Protocol
	}
	return IpProtocol_IPV4
}

func (x *IpAddress) GetMethod() IpConfigurationMethod {
	if x != nil {
		return x.Method
	}
	return IpConfigurationMethod_DHCP
}

func (x *IpAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IpAddress) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *IpAddress) GetNetmask() string {
	if x != nil {
		return x.Netmask
	}
	return ""
}

type Wifi struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to WifiState:
	//
	//	*Wifi_Unknown
	//	*Wifi_Inactive
	//	*Wifi_Active
	WifiState     isWifi_WifiState `protobuf_oneof:"wifi_state"`
	IpAddresses   []*IpAddress     `protobuf:"bytes,4,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wifi) Reset() {
	*x = Wifi{}
	mi := &file_state_wifi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wifi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wifi) ProtoMessage() {}

func (x *Wifi) ProtoReflect() protoreflect.Message {
	mi := &file_state_wifi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wifi.ProtoReflect.Descriptor instead.
func (*Wifi) Descriptor() ([]byte, []int) {
	return file_state_wifi_proto_rawDescGZIP(), []int{4}
}

func (x *Wifi) GetWifiState() isWifi_WifiState {
	if x != nil {
		return x.WifiState
	}
	return nil
}

func (x *Wifi) GetUnknown() *WifiStateUnknown {
	if x != nil {
		if x, ok := x.WifiState.(*Wifi_Unknown); ok {
			return x.Unknown
		}
	}
	return nil
}

func (x *Wifi) GetInactive() *WifiStateInactive {
	if x != nil {
		if x, ok := x.WifiState.(*Wifi_Inactive); ok {
			return x.Inactive
		}
	}
	return nil
}

func (x *Wifi) GetActive() *WifiStateActive {
	if x != nil {
		if x, ok := x.WifiState.(*Wifi_Active); ok {
			return x.Active
		}
	}
	return nil
}

func (x *Wifi) GetIpAddresses() []*IpAddress {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

type isWifi_WifiState interface {
	isWifi_WifiState()
}

type Wifi_Unknown struct {
	Unknown *WifiStateUnknown `protobuf:"bytes,1,opt,name=unknown,proto3,oneof"`
}

type Wifi_Inactive struct {
	Inactive *WifiStateInactive `protobuf:"bytes,2,opt,name=inactive,proto3,oneof"`
}

type Wifi_Active struct {
	Active *WifiStateActive `protobuf:"bytes,3,opt,name=active,proto3,oneof"`
}

func (*Wifi_Unknown) isWifi_WifiState() {}

func (*Wifi_Inactive) isWifi_WifiState() {}

func (*Wifi_Active) isWifi_WifiState() {}

var File_state_wifi_proto protoreflect.FileDescriptor

const file_state_wifi_proto_rawDesc = "" +
	"\n" +
	"\x10state/wifi.proto\x12\tBSB_State\"\x12\n" +
	"\x10WifiStateUnknown\"\x13\n" +
	"\x11WifiStateInactive\"\xd7\x01\n" +
	"\x0fWifiStateActive\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.BSB_State.WifiConnectionStatusR\x06status\x12\x12\n" +
	"\x04ssid\x18\x02 \x01(\tR\x04ssid\x12\x14\n" +
	"\x05bssid\x18\x03 \x01(\tR\x05bssid\x12\x18\n" +
	"\achannel\x18\x04 \x01(\rR\achannel\x12\x12\n" +
	"\x04rssi\x18\x05 \x01(\x11R\x04rssi\x123\n" +
	"\bsecurity\x18\x06 \x01(\x0e2\x17.BSB_State.WifiSecurityR\bsecurity\"\xc6\x01\n" +
	"\tIpAddress\x121\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x15.BSB_State.IpProtocolR\bprotocol\x128\n" +
	"\x06method\x18\x02 \x01(\x0e2 .BSB_State.IpConfigurationMethodR\x06method\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x18\n" +
	"\agateway\x18\x04 \x01(\tR\agateway\x12\x18\n" +
	"\anetmask\x18\x05 \x01(\tR\anetmask\"\xf8\x01\n" +
	"\x04Wifi\x127\n" +
	"\aunknown\x18\x01 \x01(\v2\x1b.BSB_State.WifiStateUnknownH\x00R\aunknown\x12:\n" +
	"\binactive\x18\x02 \x01(\v2\x1c.BSB_State.WifiStateInactiveH\x00R\binactive\x124\n" +
	"\x06active\x18\x03 \x01(\v2\x1a.BSB_State.WifiStateActiveH\x00R\x06active\x127\n" +
	"\fip_addresses\x18\x04 \x03(\v2\x14.BSB_State.IpAddressR\vipAddressesB\f\n" +
	"\n" +
	"wifi_state*Z\n" +
	"\x14WifiConnectionStatus\x12\r\n" +
	"\tCONNECTED\x10\x00\x12\x0e\n" +
	"\n" +
	"CONNECTING\x10\x01\x12\x11\n" +
	"\rDISCONNECTING\x10\x02\x12\x10\n" +
	"\fRECONNECTING\x10\x03*h\n" +
	"\fWifiSecurity\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\a\n" +
	"\x03WPA\x10\x02\x12\b\n" +
	"\x04WPA2\x10\x03\x12\a\n" +
	"\x03WEP\x10\x04\x12\f\n" +
	"\bWPA_WPA2\x10\x05\x12\b\n" +
	"\x04WPA3\x10\x06\x12\r\n" +
	"\tWPA2_WPA3\x10\a*-\n" +
	"\x15IpConfigurationMethod\x12\b\n" +
	"\x04DHCP\x10\x00\x12\n" +
	"\n" +
	"\x06STATIC\x10\x01* \n" +
	"\n" +
	"IpProtocol\x12\b\n" +
	"\x04IPV4\x10\x00\x12\b\n" +
	"\x04IPV6\x10\x01b\x06proto3"

var (
	file_state_wifi_proto_rawDescOnce sync.Once
	file_state_wifi_proto_rawDescData []byte
)

func file_state_wifi_proto_rawDescGZIP() []byte {
	file_state_wifi_proto_rawDescOnce.Do(func() {
		file_state_wifi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_wifi_proto_rawDesc), len(file_state_wifi_proto_rawDesc)))
	})
	return file_state_wifi_proto_rawDescData
}

var file_state_wifi_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_state_wifi_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_state_wifi_proto_goTypes = []any{
	(WifiConnectionStatus)(0),  // 0: BSB_State.WifiConnectionStatus
	(WifiSecurity)(0),          // 1: BSB_State.WifiSecurity
	(IpConfigurationMethod)(0), // 2: BSB_State.IpConfigurationMethod
	(IpProtocol)(0),            // 3: BSB_State.IpProtocol
	(*WifiStateUnknown)(nil),   // 4: BSB_State.WifiStateUnknown
	(*WifiStateInactive)(nil),  // 5: BSB_State.WifiStateInactive
	(*WifiStateActive)(nil),    // 6: BSB_State.WifiStateActive
	(*IpAddress)(nil),          // 7: BSB_State.IpAddress
	(*Wifi)(nil),               // 8: BSB_State.Wifi
}
var file_state_wifi_proto_depIdxs = []int32{
	0, // 0: BSB_State.WifiStateActive.status:type_name -> BSB_State.WifiConnectionStatus
	1, // 1: BSB_State.WifiStateActive.security:type_name -> BSB_State.WifiSecurity
	3, // 2: BSB_State.IpAddress.protocol:type_name -> BSB_State.IpProtocol
	2, // 3: BSB_State.IpAddress.method:type_name -> BSB_State.IpConfigurationMethod
	4, // 4: BSB_State.Wifi.unknown:type_name -> BSB_State.WifiStateUnknown
	5, // 5: BSB_State.Wifi.inactive:type_name -> BSB_State.WifiStateInactive
	6, // 6: BSB_State.Wifi.active:type_name -> BSB_State.WifiStateActive
	7, // 7: BSB_State.Wifi.ip_addresses:type_name -> BSB_State.IpAddress
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_state_wifi_proto_init() }
func file_state_wifi_proto_init() {
	if File_state_wifi_proto != nil {
		return
	}
	file_state_wifi_proto_msgTypes[4].OneofWrappers = []any{
		(*Wifi_Unknown)(nil),
		(*Wifi_Inactive)(nil),
		(*Wifi_Active)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_wifi_proto_rawDesc), len(file_state_wifi_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_wifi_proto_goTypes,
		DependencyIndexes: file_state_wifi_proto_depIdxs,
		EnumInfos:         file_state_wifi_proto_enumTypes,
		MessageInfos:      file_state_wifi_proto_msgTypes,
	}.Build()
	File_state_wifi_proto = out.File
	file_state_wifi_proto_goTypes = nil
	file_state_wifi_proto_depIdxs = nil
}
