// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: util/json.proto

package utilpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Compression int32

const (
	Compression_PLAIN Compression = 0
	Compression_GZIP  Compression = 1
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "PLAIN",
		1: "GZIP",
	}
	Compression_value = map[string]int32{
		"PLAIN": 0,
		"GZIP":  1,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_util_json_proto_enumTypes[0].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_util_json_proto_enumTypes[0]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_util_json_proto_rawDescGZIP(), []int{0}
}

type Json struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compression   Compression            `protobuf:"varint,1,opt,name=compression,proto3,enum=BSB_Util.Compression" json:"compression,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Json) Reset() {
	*x = Json{}
	mi := &file_util_json_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Json) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Json) ProtoMessage() {}

func (x *Json) ProtoReflect() protoreflect.Message {
	mi := &file_util_json_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Json.ProtoReflect.Descriptor instead.
func (*Json) Descriptor() ([]byte, []int) {
	return file_util_json_proto_rawDescGZIP(), []int{0}
}

func (x *Json) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_PLAIN
}

func (x *Json) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_util_json_proto protoreflect.FileDescriptor

const file_util_json_proto_rawDesc = "" +
	"\n" +
	"\x0futil/json.proto\x12\bBSB_Util\"S\n" +
	"\x04Json\x127\n" +
	"\vcompression\x18\x01 \x01(\x0e2\x15.BSB_Util.CompressionR\vcompression\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data*\"\n" +
	"\vCompression\x12\t\n" +
	"\x05PLAIN\x10\x00\x12\b\n" +
	"\x04GZIP\x10\x01b\x06proto3"

var (
	file_util_json_proto_rawDescOnce sync.Once
	file_util_json_proto_rawDescData []byte
)

func file_util_json_proto_rawDescGZIP() []byte {
	file_util_json_proto_rawDescOnce.Do(func() {
		file_util_json_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_util_json_proto_rawDesc), len(file_util_json_proto_rawDesc)))
	})
	return file_util_json_proto_rawDescData
}

var file_util_json_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_util_json_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_util_json_proto_goTypes = []any{
	(Compression)(0), // 0: BSB_Util.Compression
	(*Json)(nil),     // 1: BSB_Util.Json
}
var file_util_json_proto_depIdxs = []int32{
	0, // 0: BSB_Util.Json.compression:type_name -> BSB_Util.Compression
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_util_json_proto_init() }
func file_util_json_proto_init() {
	if File_util_json_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_util_json_proto_rawDesc), len(file_util_json_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_json_proto_goTypes,
		DependencyIndexes: file_util_json_proto_depIdxs,
		EnumInfos:         file_util_json_proto_enumTypes,
		MessageInfos:      file_util_json_proto_msgTypes,
	}.Build()
	File_util_json_proto = out.File
	file_util_json_proto_goTypes = nil
	file_util_json_proto_depIdxs = nil
}
