// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: input.proto

package inputpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Button int32

const (
	Button_OK    Button = 0
	Button_BACK  Button = 1
	Button_START Button = 2
)

// Enum value maps for Button.
var (
	Button_name = map[int32]string{
		0: "OK",
		1: "BACK",
		2: "START",
	}
	Button_value = map[string]int32{
		"OK":    0,
		"BACK":  1,
		"START": 2,
	}
)

func (x Button) Enum() *Button {
	p := new(Button)
	*p = x
	return p
}

func (x Button) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Button) Descriptor() protoreflect.EnumDescriptor {
	return file_input_proto_enumTypes[0].Descriptor()
}

func (Button) Type() protoreflect.EnumType {
	return &file_input_proto_enumTypes[0]
}

func (x Button) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Button.Descriptor instead.
func (Button) EnumDescriptor() ([]byte, []int) {
	return file_input_proto_rawDescGZIP(), []int{0}
}

type ButtonAction int32

const (
	ButtonAction_PRESS   ButtonAction = 0
	ButtonAction_RELEASE ButtonAction = 1
)

// Enum value maps for ButtonAction.
var (
	ButtonAction_name = map[int32]string{
		0: "PRESS",
		1: "RELEASE",
	}
	ButtonAction_value = map[string]int32{
		"PRESS":   0,
		"RELEASE": 1,
	}
)

func (x ButtonAction) Enum() *ButtonAction {
	p := new(ButtonAction)
	*p = x
	return p
}

func (x ButtonAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ButtonAction) Descriptor() protoreflect.EnumDescriptor {
	return file_input_proto_enumTypes[1].Descriptor()
}

func (ButtonAction) Type() protoreflect.EnumType {
	return &file_input_proto_enumTypes[1]
}

func (x ButtonAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ButtonAction.Descriptor instead.
func (ButtonAction) EnumDescriptor() ([]byte, []int) {
	return file_input_proto_rawDescGZIP(), []int{1}
}

type SwitchPosition int32

const (
	SwitchPosition_BUSY     SwitchPosition = 0
	SwitchPosition_CUSTOM   SwitchPosition = 1
	SwitchPosition_OFF      SwitchPosition = 2
	SwitchPosition_APPS     SwitchPosition = 3
	SwitchPosition_SETTINGS SwitchPosition = 4
)

// Enum value maps for SwitchPosition.
var (
	SwitchPosition_name = map[int32]string{
		0: "BUSY",
		1: "CUSTOM",
		2: "OFF",
		3: "APPS",
		4: "SETTINGS",
	}
	SwitchPosition_value = map[string]int32{
		"BUSY":     0,
		"CUSTOM":   1,
		"OFF":      2,
		"APPS":     3,
		"SETTINGS": 4,
	}
)

func (x SwitchPosition) Enum() *SwitchPosition {
	p := new(SwitchPosition)
	*p = x
	return p
}

func (x SwitchPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SwitchPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_input_proto_enumTypes[2].Descriptor()
}

func (SwitchPosition) Type() protoreflect.EnumType {
	return &file_input_proto_enumTypes[2]
}

func (x SwitchPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SwitchPosition.Descriptor instead.
func (SwitchPosition) EnumDescriptor() ([]byte, []int) {
	return file_input_proto_rawDescGZIP(), []int{2}
}

type ButtonEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Button        Button                 `protobuf:"varint,1,opt,name=button,proto3,enum=BSB_Input.Button" json:"button,omitempty"`
	Action        ButtonAction           `protobuf:"varint,2,opt,name=action,proto3,enum=BSB_Input.ButtonAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ButtonEvent) Reset() {
	*x = ButtonEvent{}
	mi := &file_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ButtonEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonEvent) ProtoMessage() {}

func (x *ButtonEvent) ProtoReflect() protoreflect.Message {
	mi := &file_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonEvent.ProtoReflect.Descriptor instead.
func (*ButtonEvent) Descriptor() ([]byte, []int) {
	return file_input_proto_rawDescGZIP(), []int{0}
}

func (x *ButtonEvent) GetButton() Button {
	if x != nil {
		return x.Button
	}
	return Button_OK
}

func (x *ButtonEvent) GetAction() ButtonAction {
	if x != nil {
		return x.Action
	}
	return ButtonAction_PRESS
}

type SwitchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      SwitchPosition         `protobuf:"varint,1,opt,name=position,proto3,enum=BSB_Input.SwitchPosition" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchEvent) Reset() {
	*x = SwitchEvent{}
	mi := &file_input_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchEvent) ProtoMessage() {}

func (x *SwitchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_input_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchEvent.ProtoReflect.Descriptor instead.
func (*SwitchEvent) Descriptor() ([]byte, []int) {
	return file_input_proto_rawDescGZIP(), []int{1}
}

func (x *SwitchEvent) GetPosition() SwitchPosition {
	if x != nil {
		return x.Position
	}
	return SwitchPosition_BUSY
}

type EncoderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         int32                  `protobuf:"zigzag32,1,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncoderEvent) Reset() {
	*x = EncoderEvent{}
	mi := &file_input_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncoderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncoderEvent) ProtoMessage() {}

func (x *EncoderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_input_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncoderEvent.ProtoReflect.Descriptor instead.
func (*EncoderEvent) Descriptor() ([]byte, []int) {
	return file_input_proto_rawDescGZIP(), []int{2}
}

func (x *EncoderEvent) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type InputEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*InputEvent_ButtonEvent
	//	*InputEvent_SwitchEvent
	//	*InputEvent_EncoderEvent
	Event         isInputEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputEvent) Reset() {
	*x = InputEvent{}
	mi := &file_input_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputEvent) ProtoMessage() {}

func (x *InputEvent) ProtoReflect() protoreflect.Message {
	mi := &file_input_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputEvent.ProtoReflect.Descriptor instead.
func (*InputEvent) Descriptor() ([]byte, []int) {
	return file_input_proto_rawDescGZIP(), []int{3}
}

func (x *InputEvent) GetEvent() isInputEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *InputEvent) GetButtonEvent() *ButtonEvent {
	if x != nil {
		if x, ok := x.Event.(*InputEvent_ButtonEvent); ok {
			return x.ButtonEvent
		}
	}
	return nil
}

func (x *InputEvent) GetSwitchEvent() *SwitchEvent {
	if x != nil {
		if x, ok := x.Event.(*InputEvent_SwitchEvent); ok {
			return x.SwitchEvent
		}
	}
	return nil
}

func (x *InputEvent) GetEncoderEvent() *EncoderEvent {
	if x != nil {
		if x, ok := x.Event.(*InputEvent_EncoderEvent); ok {
			return x.EncoderEvent
		}
	}
	return nil
}

type isInputEvent_Event interface {
	isInputEvent_Event()
}

type InputEvent_ButtonEvent struct {
	ButtonEvent *ButtonEvent `protobuf:"bytes,1,opt,name=button_event,json=buttonEvent,proto3,oneof"`
}

type InputEvent_SwitchEvent struct {
	SwitchEvent *SwitchEvent `protobuf:"bytes,2,opt,name=switch_event,json=switchEvent,proto3,oneof"`
}

type InputEvent_EncoderEvent struct {
	EncoderEvent *EncoderEvent `protobuf:"bytes,3,opt,name=encoder_event,json=encoderEvent,proto3,oneof"`
}

func (*InputEvent_ButtonEvent) isInputEvent_Event() {}

func (*InputEvent_SwitchEvent) isInputEvent_Event() {}

func (*InputEvent_EncoderEvent) isInputEvent_Event() {}

var File_input_proto protoreflect.FileDescriptor

const file_input_proto_rawDesc = "" +
	"\n" +
	"\vinput.proto\x12\tBSB_Input\"i\n" +
	"\vButtonEvent\x12)\n" +
	"\x06button\x18\x01 \x01(\x0e2\x11.BSB_Input.ButtonR\x06button\x12/\n" +
	"\x06action\x18\x02 \x01(\x0e2\x17.BSB_Input.ButtonActionR\x06action\"D\n" +
	"\vSwitchEvent\x125\n" +
	"\bposition\x18\x01 \x01(\x0e2\x19.BSB_Input.SwitchPositionR\bposition\"$\n" +
	"\fEncoderEvent\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\x11R\x05delta\"\xcf\x01\n" +
	"\n" +
	"InputEvent\x12;\n" +
	"\fbutton_event\x18\x01 \x01(\v2\x16.BSB_Input.ButtonEventH\x00R\vbuttonEvent\x12;\n" +
	"\fswitch_event\x18\x02 \x01(\v2\x16.BSB_Input.SwitchEventH\x00R\vswitchEvent\x12>\n" +
	"\rencoder_event\x18\x03 \x01(\v2\x17.BSB_Input.EncoderEventH\x00R\fencoderEventB\a\n" +
	"\x05event*%\n" +
	"\x06Button\x12\x06\n" +
	"\x02OK\x10\x00\x12\b\n" +
	"\x04BACK\x10\x01\x12\t\n" +
	"\x05START\x10\x02*&\n" +
	"\fButtonAction\x12\t\n" +
	"\x05PRESS\x10\x00\x12\v\n" +
	"\aRELEASE\x10\x01*G\n" +
	"\x0eSwitchPosition\x12\b\n" +
	"\x04BUSY\x10\x00\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x01\x12\a\n" +
	"\x03OFF\x10\x02\x12\b\n" +
	"\x04APPS\x10\x03\x12\f\n" +
	"\bSETTINGS\x10\x04b\x06proto3"

var (
	file_input_proto_rawDescOnce sync.Once
	file_input_proto_rawDescData []byte
)

func file_input_proto_rawDescGZIP() []byte {
	file_input_proto_rawDescOnce.Do(func() {
		file_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_input_proto_rawDesc), len(file_input_proto_rawDesc)))
	})
	return file_input_proto_rawDescData
}

var file_input_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_input_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_input_proto_goTypes = []any{
	(Button)(0),          // 0: BSB_Input.Button
	(ButtonAction)(0),    // 1: BSB_Input.ButtonAction
	(SwitchPosition)(0),  // 2: BSB_Input.SwitchPosition
	(*ButtonEvent)(nil),  // 3: BSB_Input.ButtonEvent
	(*SwitchEvent)(nil),  // 4: BSB_Input.SwitchEvent
	(*EncoderEvent)(nil), // 5: BSB_Input.EncoderEvent
	(*InputEvent)(nil),   // 6: BSB_Input.InputEvent
}
var file_input_proto_depIdxs = []int32{
	0, // 0: BSB_Input.ButtonEvent.button:type_name -> BSB_Input.Button
	1, // 1: BSB_Input.ButtonEvent.action:type_name -> BSB_Input.ButtonAction
	2, // 2: BSB_Input.SwitchEvent.position:type_name -> BSB_Input.SwitchPosition
	3, // 3: BSB_Input.InputEvent.button_event:type_name -> BSB_Input.ButtonEvent
	4, // 4: BSB_Input.InputEvent.switch_event:type_name -> BSB_Input.SwitchEvent
	5, // 5: BSB_Input.InputEvent.encoder_event:type_name -> BSB_Input.EncoderEvent
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_input_proto_init() }
func file_input_proto_init() {
	if File_input_proto != nil {
		return
	}
	file_input_proto_msgTypes[3].OneofWrappers = []any{
		(*InputEvent_ButtonEvent)(nil),
		(*InputEvent_SwitchEvent)(nil),
		(*InputEvent_EncoderEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_input_proto_rawDesc), len(file_input_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_input_proto_goTypes,
		DependencyIndexes: file_input_proto_depIdxs,
		EnumInfos:         file_input_proto_enumTypes,
		MessageInfos:      file_input_proto_msgTypes,
	}.Build()
	File_input_proto = out.File
	file_input_proto_goTypes = nil
	file_input_proto_depIdxs = nil
}
