// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: state/update.proto

package updatepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateEvent int32

const (
	UpdateEvent_SESSION_START   UpdateEvent = 0 // Update process started (lock acquired)
	UpdateEvent_SESSION_STOP    UpdateEvent = 1 // Update process stopped (lock released)
	UpdateEvent_ACTION_BEGIN    UpdateEvent = 2 // Action started (download/unpack/prepare/reboot)
	UpdateEvent_ACTION_DONE     UpdateEvent = 3 // Action completed with result status
	UpdateEvent_DETAIL_CHANGE   UpdateEvent = 4 // Status detail string changed (e.g., download state message)
	UpdateEvent_ACTION_PROGRESS UpdateEvent = 5 // Progress update (e.g., download bytes received)
	UpdateEvent_EVENT_NONE      UpdateEvent = 6 // No event (initial/idle state)
)

// Enum value maps for UpdateEvent.
var (
	UpdateEvent_name = map[int32]string{
		0: "SESSION_START",
		1: "SESSION_STOP",
		2: "ACTION_BEGIN",
		3: "ACTION_DONE",
		4: "DETAIL_CHANGE",
		5: "ACTION_PROGRESS",
		6: "EVENT_NONE",
	}
	UpdateEvent_value = map[string]int32{
		"SESSION_START":   0,
		"SESSION_STOP":    1,
		"ACTION_BEGIN":    2,
		"ACTION_DONE":     3,
		"DETAIL_CHANGE":   4,
		"ACTION_PROGRESS": 5,
		"EVENT_NONE":      6,
	}
)

func (x UpdateEvent) Enum() *UpdateEvent {
	p := new(UpdateEvent)
	*p = x
	return p
}

func (x UpdateEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_state_update_proto_enumTypes[0].Descriptor()
}

func (UpdateEvent) Type() protoreflect.EnumType {
	return &file_state_update_proto_enumTypes[0]
}

func (x UpdateEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateEvent.Descriptor instead.
func (UpdateEvent) EnumDescriptor() ([]byte, []int) {
	return file_state_update_proto_rawDescGZIP(), []int{0}
}

type UpdateAction int32

const (
	UpdateAction_DOWNLOAD             UpdateAction = 0 // Downloading update bundle from URL
	UpdateAction_SHA_VERIFICATION     UpdateAction = 1 // Downloading update bundle from URL
	UpdateAction_UNPACK               UpdateAction = 2 // Unpacking .tar archive to staging directory
	UpdateAction_INSTALLATION_PREPARE UpdateAction = 3 // Preparing update for installation (manifest validation, session setup)
	UpdateAction_INSTALLATION_APPLY   UpdateAction = 4 // Rebooting device to install prepared update
	UpdateAction_ACTION_NONE          UpdateAction = 5 // No action (initial/idle state)
)

// Enum value maps for UpdateAction.
var (
	UpdateAction_name = map[int32]string{
		0: "DOWNLOAD",
		1: "SHA_VERIFICATION",
		2: "UNPACK",
		3: "INSTALLATION_PREPARE",
		4: "INSTALLATION_APPLY",
		5: "ACTION_NONE",
	}
	UpdateAction_value = map[string]int32{
		"DOWNLOAD":             0,
		"SHA_VERIFICATION":     1,
		"UNPACK":               2,
		"INSTALLATION_PREPARE": 3,
		"INSTALLATION_APPLY":   4,
		"ACTION_NONE":          5,
	}
)

func (x UpdateAction) Enum() *UpdateAction {
	p := new(UpdateAction)
	*p = x
	return p
}

func (x UpdateAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateAction) Descriptor() protoreflect.EnumDescriptor {
	return file_state_update_proto_enumTypes[1].Descriptor()
}

func (UpdateAction) Type() protoreflect.EnumType {
	return &file_state_update_proto_enumTypes[1]
}

func (x UpdateAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateAction.Descriptor instead.
func (UpdateAction) EnumDescriptor() ([]byte, []int) {
	return file_state_update_proto_rawDescGZIP(), []int{1}
}

type UpdateStatus int32

const (
	UpdateStatus_OK                                                UpdateStatus = 0  // Operation completed successfully
	UpdateStatus_BATTERY_LOW                                       UpdateStatus = 1  // Battery level too low
	UpdateStatus_BUSY                                              UpdateStatus = 2  // Update already in progress
	UpdateStatus_DOWNLOAD_FAILURE                                  UpdateStatus = 3  // Failed to download update bundle from URL
	UpdateStatus_DOWNLOAD_ABORT                                    UpdateStatus = 4  // Download was aborted by user
	UpdateStatus_SHA_MISMATCH                                      UpdateStatus = 5  // Update bundle SHA256 checksum verification failed
	UpdateStatus_UNPACK_CREATE_STAGING_DIRECTORY_FAILURE           UpdateStatus = 6  // Failed to create staging directory
	UpdateStatus_UNPACK_ARCHIVE_OPEN_FAILURE                       UpdateStatus = 7  // Failed to open .tar archive file
	UpdateStatus_UNPACK_ARCHIVE_UNPACK_FAILURE                     UpdateStatus = 8  // Failed to extract .tar archive contents
	UpdateStatus_INSTALLATION_PREPARE_MANIFEST_NOT_FOUND           UpdateStatus = 9  // Update manifest file not found
	UpdateStatus_INSTALLATION_PREPARE_MANIFEST_INVALID             UpdateStatus = 10 // Manifest file validation failed
	UpdateStatus_INSTALLATION_PREPARE_SESSION_CONFIG_SETUP_FAILURE UpdateStatus = 11 // Failed to save session configuration
	UpdateStatus_INSTALLATION_PREPARE_POINTER_SETUP_FAILURE        UpdateStatus = 12 // Failed to write pointer file
	UpdateStatus_UNKNOWN_FAILURE                                   UpdateStatus = 13 // Unknown error occurred
)

// Enum value maps for UpdateStatus.
var (
	UpdateStatus_name = map[int32]string{
		0:  "OK",
		1:  "BATTERY_LOW",
		2:  "BUSY",
		3:  "DOWNLOAD_FAILURE",
		4:  "DOWNLOAD_ABORT",
		5:  "SHA_MISMATCH",
		6:  "UNPACK_CREATE_STAGING_DIRECTORY_FAILURE",
		7:  "UNPACK_ARCHIVE_OPEN_FAILURE",
		8:  "UNPACK_ARCHIVE_UNPACK_FAILURE",
		9:  "INSTALLATION_PREPARE_MANIFEST_NOT_FOUND",
		10: "INSTALLATION_PREPARE_MANIFEST_INVALID",
		11: "INSTALLATION_PREPARE_SESSION_CONFIG_SETUP_FAILURE",
		12: "INSTALLATION_PREPARE_POINTER_SETUP_FAILURE",
		13: "UNKNOWN_FAILURE",
	}
	UpdateStatus_value = map[string]int32{
		"OK":               0,
		"BATTERY_LOW":      1,
		"BUSY":             2,
		"DOWNLOAD_FAILURE": 3,
		"DOWNLOAD_ABORT":   4,
		"SHA_MISMATCH":     5,
		"UNPACK_CREATE_STAGING_DIRECTORY_FAILURE":           6,
		"UNPACK_ARCHIVE_OPEN_FAILURE":                       7,
		"UNPACK_ARCHIVE_UNPACK_FAILURE":                     8,
		"INSTALLATION_PREPARE_MANIFEST_NOT_FOUND":           9,
		"INSTALLATION_PREPARE_MANIFEST_INVALID":             10,
		"INSTALLATION_PREPARE_SESSION_CONFIG_SETUP_FAILURE": 11,
		"INSTALLATION_PREPARE_POINTER_SETUP_FAILURE":        12,
		"UNKNOWN_FAILURE":                                   13,
	}
)

func (x UpdateStatus) Enum() *UpdateStatus {
	p := new(UpdateStatus)
	*p = x
	return p
}

func (x UpdateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_state_update_proto_enumTypes[2].Descriptor()
}

func (UpdateStatus) Type() protoreflect.EnumType {
	return &file_state_update_proto_enumTypes[2]
}

func (x UpdateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateStatus.Descriptor instead.
func (UpdateStatus) EnumDescriptor() ([]byte, []int) {
	return file_state_update_proto_rawDescGZIP(), []int{2}
}

type CheckError int32

const (
	CheckError_NOT_AVAILABLE CheckError = 0 // No update available
	CheckError_FAILURE       CheckError = 1 // Failed to check for update
	CheckError_IDLE          CheckError = 2 // No check performed (initial/idle state)
)

// Enum value maps for CheckError.
var (
	CheckError_name = map[int32]string{
		0: "NOT_AVAILABLE",
		1: "FAILURE",
		2: "IDLE",
	}
	CheckError_value = map[string]int32{
		"NOT_AVAILABLE": 0,
		"FAILURE":       1,
		"IDLE":          2,
	}
)

func (x CheckError) Enum() *CheckError {
	p := new(CheckError)
	*p = x
	return p
}

func (x CheckError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckError) Descriptor() protoreflect.EnumDescriptor {
	return file_state_update_proto_enumTypes[3].Descriptor()
}

func (CheckError) Type() protoreflect.EnumType {
	return &file_state_update_proto_enumTypes[3]
}

func (x CheckError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckError.Descriptor instead.
func (CheckError) EnumDescriptor() ([]byte, []int) {
	return file_state_update_proto_rawDescGZIP(), []int{3}
}

type CheckEvent int32

const (
	CheckEvent_START CheckEvent = 0 // Update check started
	CheckEvent_STOP  CheckEvent = 1 // Update check stopped
	CheckEvent_NONE  CheckEvent = 2 // No event (initial/idle state)
)

// Enum value maps for CheckEvent.
var (
	CheckEvent_name = map[int32]string{
		0: "START",
		1: "STOP",
		2: "NONE",
	}
	CheckEvent_value = map[string]int32{
		"START": 0,
		"STOP":  1,
		"NONE":  2,
	}
)

func (x CheckEvent) Enum() *CheckEvent {
	p := new(CheckEvent)
	*p = x
	return p
}

func (x CheckEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_state_update_proto_enumTypes[4].Descriptor()
}

func (CheckEvent) Type() protoreflect.EnumType {
	return &file_state_update_proto_enumTypes[4]
}

func (x CheckEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckEvent.Descriptor instead.
func (CheckEvent) EnumDescriptor() ([]byte, []int) {
	return file_state_update_proto_rawDescGZIP(), []int{4}
}

type UpdateAvailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvailable) Reset() {
	*x = UpdateAvailable{}
	mi := &file_state_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvailable) ProtoMessage() {}

func (x *UpdateAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_state_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvailable.ProtoReflect.Descriptor instead.
func (*UpdateAvailable) Descriptor() ([]byte, []int) {
	return file_state_update_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateAvailable) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UpdateUnavailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        CheckError             `protobuf:"varint,1,opt,name=reason,proto3,enum=BSB_Update.CheckError" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUnavailable) Reset() {
	*x = UpdateUnavailable{}
	mi := &file_state_update_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUnavailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUnavailable) ProtoMessage() {}

func (x *UpdateUnavailable) ProtoReflect() protoreflect.Message {
	mi := &file_state_update_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUnavailable.ProtoReflect.Descriptor instead.
func (*UpdateUnavailable) Descriptor() ([]byte, []int) {
	return file_state_update_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUnavailable) GetReason() CheckError {
	if x != nil {
		return x.Reason
	}
	return CheckError_NOT_AVAILABLE
}

type UpdateState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         UpdateEvent            `protobuf:"varint,1,opt,name=event,proto3,enum=BSB_Update.UpdateEvent" json:"event,omitempty"`
	Action        UpdateAction           `protobuf:"varint,2,opt,name=action,proto3,enum=BSB_Update.UpdateAction" json:"action,omitempty"`
	Status        UpdateStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=BSB_Update.UpdateStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateState) Reset() {
	*x = UpdateState{}
	mi := &file_state_update_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateState) ProtoMessage() {}

func (x *UpdateState) ProtoReflect() protoreflect.Message {
	mi := &file_state_update_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateState.ProtoReflect.Descriptor instead.
func (*UpdateState) Descriptor() ([]byte, []int) {
	return file_state_update_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateState) GetEvent() UpdateEvent {
	if x != nil {
		return x.Event
	}
	return UpdateEvent_SESSION_START
}

func (x *UpdateState) GetAction() UpdateAction {
	if x != nil {
		return x.Action
	}
	return UpdateAction_DOWNLOAD
}

func (x *UpdateState) GetStatus() UpdateStatus {
	if x != nil {
		return x.Status
	}
	return UpdateStatus_OK
}

type CheckState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Event CheckEvent             `protobuf:"varint,3,opt,name=event,proto3,enum=BSB_Update.CheckEvent" json:"event,omitempty"`
	// Types that are valid to be assigned to Status:
	//
	//	*CheckState_Available
	//	*CheckState_Unavailable
	Status        isCheckState_Status `protobuf_oneof:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckState) Reset() {
	*x = CheckState{}
	mi := &file_state_update_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckState) ProtoMessage() {}

func (x *CheckState) ProtoReflect() protoreflect.Message {
	mi := &file_state_update_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckState.ProtoReflect.Descriptor instead.
func (*CheckState) Descriptor() ([]byte, []int) {
	return file_state_update_proto_rawDescGZIP(), []int{3}
}

func (x *CheckState) GetEvent() CheckEvent {
	if x != nil {
		return x.Event
	}
	return CheckEvent_START
}

func (x *CheckState) GetStatus() isCheckState_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CheckState) GetAvailable() *UpdateAvailable {
	if x != nil {
		if x, ok := x.Status.(*CheckState_Available); ok {
			return x.Available
		}
	}
	return nil
}

func (x *CheckState) GetUnavailable() *UpdateUnavailable {
	if x != nil {
		if x, ok := x.Status.(*CheckState_Unavailable); ok {
			return x.Unavailable
		}
	}
	return nil
}

type isCheckState_Status interface {
	isCheckState_Status()
}

type CheckState_Available struct {
	Available *UpdateAvailable `protobuf:"bytes,1,opt,name=available,proto3,oneof"`
}

type CheckState_Unavailable struct {
	Unavailable *UpdateUnavailable `protobuf:"bytes,2,opt,name=unavailable,proto3,oneof"`
}

func (*CheckState_Available) isCheckState_Status() {}

func (*CheckState_Unavailable) isCheckState_Status() {}

type AutoUpdateInterval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint32                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // minutes since midnight
	End           uint32                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`     // minutes since midnight
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoUpdateInterval) Reset() {
	*x = AutoUpdateInterval{}
	mi := &file_state_update_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoUpdateInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoUpdateInterval) ProtoMessage() {}

func (x *AutoUpdateInterval) ProtoReflect() protoreflect.Message {
	mi := &file_state_update_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoUpdateInterval.ProtoReflect.Descriptor instead.
func (*AutoUpdateInterval) Descriptor() ([]byte, []int) {
	return file_state_update_proto_rawDescGZIP(), []int{4}
}

func (x *AutoUpdateInterval) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *AutoUpdateInterval) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

type AutoUpdateState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Interval      *AutoUpdateInterval    `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoUpdateState) Reset() {
	*x = AutoUpdateState{}
	mi := &file_state_update_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoUpdateState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoUpdateState) ProtoMessage() {}

func (x *AutoUpdateState) ProtoReflect() protoreflect.Message {
	mi := &file_state_update_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoUpdateState.ProtoReflect.Descriptor instead.
func (*AutoUpdateState) Descriptor() ([]byte, []int) {
	return file_state_update_proto_rawDescGZIP(), []int{5}
}

func (x *AutoUpdateState) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AutoUpdateState) GetInterval() *AutoUpdateInterval {
	if x != nil {
		return x.Interval
	}
	return nil
}

var File_state_update_proto protoreflect.FileDescriptor

const file_state_update_proto_rawDesc = "" +
	"\n" +
	"\x12state/update.proto\x12\n" +
	"BSB_Update\"+\n" +
	"\x0fUpdateAvailable\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"C\n" +
	"\x11UpdateUnavailable\x12.\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x16.BSB_Update.CheckErrorR\x06reason\"\xa0\x01\n" +
	"\vUpdateState\x12-\n" +
	"\x05event\x18\x01 \x01(\x0e2\x17.BSB_Update.UpdateEventR\x05event\x120\n" +
	"\x06action\x18\x02 \x01(\x0e2\x18.BSB_Update.UpdateActionR\x06action\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.BSB_Update.UpdateStatusR\x06status\"\xc4\x01\n" +
	"\n" +
	"CheckState\x12,\n" +
	"\x05event\x18\x03 \x01(\x0e2\x16.BSB_Update.CheckEventR\x05event\x12;\n" +
	"\tavailable\x18\x01 \x01(\v2\x1b.BSB_Update.UpdateAvailableH\x00R\tavailable\x12A\n" +
	"\vunavailable\x18\x02 \x01(\v2\x1d.BSB_Update.UpdateUnavailableH\x00R\vunavailableB\b\n" +
	"\x06status\"<\n" +
	"\x12AutoUpdateInterval\x12\x14\n" +
	"\x05start\x18\x01 \x01(\rR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\rR\x03end\"g\n" +
	"\x0fAutoUpdateState\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12:\n" +
	"\binterval\x18\x02 \x01(\v2\x1e.BSB_Update.AutoUpdateIntervalR\binterval*\x8d\x01\n" +
	"\vUpdateEvent\x12\x11\n" +
	"\rSESSION_START\x10\x00\x12\x10\n" +
	"\fSESSION_STOP\x10\x01\x12\x10\n" +
	"\fACTION_BEGIN\x10\x02\x12\x0f\n" +
	"\vACTION_DONE\x10\x03\x12\x11\n" +
	"\rDETAIL_CHANGE\x10\x04\x12\x13\n" +
	"\x0fACTION_PROGRESS\x10\x05\x12\x0e\n" +
	"\n" +
	"EVENT_NONE\x10\x06*\x81\x01\n" +
	"\fUpdateAction\x12\f\n" +
	"\bDOWNLOAD\x10\x00\x12\x14\n" +
	"\x10SHA_VERIFICATION\x10\x01\x12\n" +
	"\n" +
	"\x06UNPACK\x10\x02\x12\x18\n" +
	"\x14INSTALLATION_PREPARE\x10\x03\x12\x16\n" +
	"\x12INSTALLATION_APPLY\x10\x04\x12\x0f\n" +
	"\vACTION_NONE\x10\x05*\xb2\x03\n" +
	"\fUpdateStatus\x12\x06\n" +
	"\x02OK\x10\x00\x12\x0f\n" +
	"\vBATTERY_LOW\x10\x01\x12\b\n" +
	"\x04BUSY\x10\x02\x12\x14\n" +
	"\x10DOWNLOAD_FAILURE\x10\x03\x12\x12\n" +
	"\x0eDOWNLOAD_ABORT\x10\x04\x12\x10\n" +
	"\fSHA_MISMATCH\x10\x05\x12+\n" +
	"'UNPACK_CREATE_STAGING_DIRECTORY_FAILURE\x10\x06\x12\x1f\n" +
	"\x1bUNPACK_ARCHIVE_OPEN_FAILURE\x10\a\x12!\n" +
	"\x1dUNPACK_ARCHIVE_UNPACK_FAILURE\x10\b\x12+\n" +
	"'INSTALLATION_PREPARE_MANIFEST_NOT_FOUND\x10\t\x12)\n" +
	"%INSTALLATION_PREPARE_MANIFEST_INVALID\x10\n" +
	"\x125\n" +
	"1INSTALLATION_PREPARE_SESSION_CONFIG_SETUP_FAILURE\x10\v\x12.\n" +
	"*INSTALLATION_PREPARE_POINTER_SETUP_FAILURE\x10\f\x12\x13\n" +
	"\x0fUNKNOWN_FAILURE\x10\r*6\n" +
	"\n" +
	"CheckError\x12\x11\n" +
	"\rNOT_AVAILABLE\x10\x00\x12\v\n" +
	"\aFAILURE\x10\x01\x12\b\n" +
	"\x04IDLE\x10\x02*+\n" +
	"\n" +
	"CheckEvent\x12\t\n" +
	"\x05START\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\x12\b\n" +
	"\x04NONE\x10\x02b\x06proto3"

var (
	file_state_update_proto_rawDescOnce sync.Once
	file_state_update_proto_rawDescData []byte
)

func file_state_update_proto_rawDescGZIP() []byte {
	file_state_update_proto_rawDescOnce.Do(func() {
		file_state_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_update_proto_rawDesc), len(file_state_update_proto_rawDesc)))
	})
	return file_state_update_proto_rawDescData
}

var file_state_update_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_state_update_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_state_update_proto_goTypes = []any{
	(UpdateEvent)(0),           // 0: BSB_Update.UpdateEvent
	(UpdateAction)(0),          // 1: BSB_Update.UpdateAction
	(UpdateStatus)(0),          // 2: BSB_Update.UpdateStatus
	(CheckError)(0),            // 3: BSB_Update.CheckError
	(CheckEvent)(0),            // 4: BSB_Update.CheckEvent
	(*UpdateAvailable)(nil),    // 5: BSB_Update.UpdateAvailable
	(*UpdateUnavailable)(nil),  // 6: BSB_Update.UpdateUnavailable
	(*UpdateState)(nil),        // 7: BSB_Update.UpdateState
	(*CheckState)(nil),         // 8: BSB_Update.CheckState
	(*AutoUpdateInterval)(nil), // 9: BSB_Update.AutoUpdateInterval
	(*AutoUpdateState)(nil),    // 10: BSB_Update.AutoUpdateState
}
var file_state_update_proto_depIdxs = []int32{
	3, // 0: BSB_Update.UpdateUnavailable.reason:type_name -> BSB_Update.CheckError
	0, // 1: BSB_Update.UpdateState.event:type_name -> BSB_Update.UpdateEvent
	1, // 2: BSB_Update.UpdateState.action:type_name -> BSB_Update.UpdateAction
	2, // 3: BSB_Update.UpdateState.status:type_name -> BSB_Update.UpdateStatus
	4, // 4: BSB_Update.CheckState.event:type_name -> BSB_Update.CheckEvent
	5, // 5: BSB_Update.CheckState.available:type_name -> BSB_Update.UpdateAvailable
	6, // 6: BSB_Update.CheckState.unavailable:type_name -> BSB_Update.UpdateUnavailable
	9, // 7: BSB_Update.AutoUpdateState.interval:type_name -> BSB_Update.AutoUpdateInterval
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_state_update_proto_init() }
func file_state_update_proto_init() {
	if File_state_update_proto != nil {
		return
	}
	file_state_update_proto_msgTypes[3].OneofWrappers = []any{
		(*CheckState_Available)(nil),
		(*CheckState_Unavailable)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_update_proto_rawDesc), len(file_state_update_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_update_proto_goTypes,
		DependencyIndexes: file_state_update_proto_depIdxs,
		EnumInfos:         file_state_update_proto_enumTypes,
		MessageInfos:      file_state_update_proto_msgTypes,
	}.Build()
	File_state_update_proto = out.File
	file_state_update_proto_goTypes = nil
	file_state_update_proto_depIdxs = nil
}
