// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: frame.proto

package framepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Encoding int32

const (
	Encoding_PLAIN              Encoding = 0
	Encoding_RUN_LENGTH         Encoding = 1
	Encoding_DEFLATE            Encoding = 2
	Encoding_DEFLATE_RUN_LENGTH Encoding = 3
)

// Enum value maps for Encoding.
var (
	Encoding_name = map[int32]string{
		0: "PLAIN",
		1: "RUN_LENGTH",
		2: "DEFLATE",
		3: "DEFLATE_RUN_LENGTH",
	}
	Encoding_value = map[string]int32{
		"PLAIN":              0,
		"RUN_LENGTH":         1,
		"DEFLATE":            2,
		"DEFLATE_RUN_LENGTH": 3,
	}
)

func (x Encoding) Enum() *Encoding {
	p := new(Encoding)
	*p = x
	return p
}

func (x Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_frame_proto_enumTypes[0].Descriptor()
}

func (Encoding) Type() protoreflect.EnumType {
	return &file_frame_proto_enumTypes[0]
}

func (x Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encoding.Descriptor instead.
func (Encoding) EnumDescriptor() ([]byte, []int) {
	return file_frame_proto_rawDescGZIP(), []int{0}
}

type PixelFormat int32

const (
	PixelFormat_RGB888 PixelFormat = 0
	PixelFormat_L8     PixelFormat = 1
	PixelFormat_L4     PixelFormat = 2
)

// Enum value maps for PixelFormat.
var (
	PixelFormat_name = map[int32]string{
		0: "RGB888",
		1: "L8",
		2: "L4",
	}
	PixelFormat_value = map[string]int32{
		"RGB888": 0,
		"L8":     1,
		"L4":     2,
	}
)

func (x PixelFormat) Enum() *PixelFormat {
	p := new(PixelFormat)
	*p = x
	return p
}

func (x PixelFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PixelFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_frame_proto_enumTypes[1].Descriptor()
}

func (PixelFormat) Type() protoreflect.EnumType {
	return &file_frame_proto_enumTypes[1]
}

func (x PixelFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PixelFormat.Descriptor instead.
func (PixelFormat) EnumDescriptor() ([]byte, []int) {
	return file_frame_proto_rawDescGZIP(), []int{1}
}

type Screen int32

const (
	Screen_FRONT Screen = 0
	Screen_BACK  Screen = 1
)

// Enum value maps for Screen.
var (
	Screen_name = map[int32]string{
		0: "FRONT",
		1: "BACK",
	}
	Screen_value = map[string]int32{
		"FRONT": 0,
		"BACK":  1,
	}
)

func (x Screen) Enum() *Screen {
	p := new(Screen)
	*p = x
	return p
}

func (x Screen) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Screen) Descriptor() protoreflect.EnumDescriptor {
	return file_frame_proto_enumTypes[2].Descriptor()
}

func (Screen) Type() protoreflect.EnumType {
	return &file_frame_proto_enumTypes[2]
}

func (x Screen) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Screen.Descriptor instead.
func (Screen) EnumDescriptor() ([]byte, []int) {
	return file_frame_proto_rawDescGZIP(), []int{2}
}

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Screen        Screen                 `protobuf:"varint,1,opt,name=screen,proto3,enum=BSB_Frame.Screen" json:"screen,omitempty"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Encoding      Encoding               `protobuf:"varint,4,opt,name=encoding,proto3,enum=BSB_Frame.Encoding" json:"encoding,omitempty"`
	PixelFormat   PixelFormat            `protobuf:"varint,5,opt,name=pixel_format,json=pixelFormat,proto3,enum=BSB_Frame.PixelFormat" json:"pixel_format,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_frame_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetScreen() Screen {
	if x != nil {
		return x.Screen
	}
	return Screen_FRONT
}

func (x *Frame) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Frame) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Frame) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_PLAIN
}

func (x *Frame) GetPixelFormat() PixelFormat {
	if x != nil {
		return x.PixelFormat
	}
	return PixelFormat_RGB888
}

func (x *Frame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_frame_proto protoreflect.FileDescriptor

const file_frame_proto_rawDesc = "" +
	"\n" +
	"\vframe.proto\x12\tBSB_Frame\"\xe0\x01\n" +
	"\x05Frame\x12)\n" +
	"\x06screen\x18\x01 \x01(\x0e2\x11.BSB_Frame.ScreenR\x06screen\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12/\n" +
	"\bencoding\x18\x04 \x01(\x0e2\x13.BSB_Frame.EncodingR\bencoding\x129\n" +
	"\fpixel_format\x18\x05 \x01(\x0e2\x16.BSB_Frame.PixelFormatR\vpixelFormat\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data*J\n" +
	"\bEncoding\x12\t\n" +
	"\x05PLAIN\x10\x00\x12\x0e\n" +
	"\n" +
	"RUN_LENGTH\x10\x01\x12\v\n" +
	"\aDEFLATE\x10\x02\x12\x16\n" +
	"\x12DEFLATE_RUN_LENGTH\x10\x03*)\n" +
	"\vPixelFormat\x12\n" +
	"\n" +
	"\x06RGB888\x10\x00\x12\x06\n" +
	"\x02L8\x10\x01\x12\x06\n" +
	"\x02L4\x10\x02*\x1d\n" +
	"\x06Screen\x12\t\n" +
	"\x05FRONT\x10\x00\x12\b\n" +
	"\x04BACK\x10\x01b\x06proto3"

var (
	file_frame_proto_rawDescOnce sync.Once
	file_frame_proto_rawDescData []byte
)

func file_frame_proto_rawDescGZIP() []byte {
	file_frame_proto_rawDescOnce.Do(func() {
		file_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frame_proto_rawDesc), len(file_frame_proto_rawDesc)))
	})
	return file_frame_proto_rawDescData
}

var file_frame_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_frame_proto_goTypes = []any{
	(Encoding)(0),    // 0: BSB_Frame.Encoding
	(PixelFormat)(0), // 1: BSB_Frame.PixelFormat
	(Screen)(0),      // 2: BSB_Frame.Screen
	(*Frame)(nil),    // 3: BSB_Frame.Frame
}
var file_frame_proto_depIdxs = []int32{
	2, // 0: BSB_Frame.Frame.screen:type_name -> BSB_Frame.Screen
	0, // 1: BSB_Frame.Frame.encoding:type_name -> BSB_Frame.Encoding
	1, // 2: BSB_Frame.Frame.pixel_format:type_name -> BSB_Frame.PixelFormat
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_frame_proto_init() }
func file_frame_proto_init() {
	if File_frame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frame_proto_rawDesc), len(file_frame_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frame_proto_goTypes,
		DependencyIndexes: file_frame_proto_depIdxs,
		EnumInfos:         file_frame_proto_enumTypes,
		MessageInfos:      file_frame_proto_msgTypes,
	}.Build()
	File_frame_proto = out.File
	file_frame_proto_goTypes = nil
	file_frame_proto_depIdxs = nil
}
