// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: state/ble.proto

package blepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceStatus int32

const (
	ServiceStatus_RESET          ServiceStatus = 0 // Service has just been created. Will move to INITIALIZATION when it creates all inner objects.
	ServiceStatus_INITIALIZATION ServiceStatus = 1 // Service performs initialization sequence for all inner ble services. U5 also sends init data to 917 to help it create its services.
	ServiceStatus_READY          ServiceStatus = 2 // All init sequences are done. All inner services configured, and both u5 and 917 are ready to work. But ble is still disabled.
	ServiceStatus_ADVERTISING    ServiceStatus = 3 // Ble enabled, device is not paired and is visible to all.
	ServiceStatus_CONNECTABLE    ServiceStatus = 4 // Ble enabled, device is paired and waits for a remote device to connect.
	ServiceStatus_CONNECTED      ServiceStatus = 5 // Remote device connected.
	ServiceStatus_ERROR          ServiceStatus = 6 // Internal error.
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "RESET",
		1: "INITIALIZATION",
		2: "READY",
		3: "ADVERTISING",
		4: "CONNECTABLE",
		5: "CONNECTED",
		6: "ERROR",
	}
	ServiceStatus_value = map[string]int32{
		"RESET":          0,
		"INITIALIZATION": 1,
		"READY":          2,
		"ADVERTISING":    3,
		"CONNECTABLE":    4,
		"CONNECTED":      5,
		"ERROR":          6,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_state_ble_proto_enumTypes[0].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_state_ble_proto_enumTypes[0]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_state_ble_proto_rawDescGZIP(), []int{0}
}

type Ble struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ServiceStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=BSB_State.Ble.ServiceStatus" json:"status,omitempty"`
	RemoteAddress *string                `protobuf:"bytes,2,opt,name=remote_address,json=remoteAddress,proto3,oneof" json:"remote_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ble) Reset() {
	*x = Ble{}
	mi := &file_state_ble_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ble) ProtoMessage() {}

func (x *Ble) ProtoReflect() protoreflect.Message {
	mi := &file_state_ble_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ble.ProtoReflect.Descriptor instead.
func (*Ble) Descriptor() ([]byte, []int) {
	return file_state_ble_proto_rawDescGZIP(), []int{0}
}

func (x *Ble) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_RESET
}

func (x *Ble) GetRemoteAddress() string {
	if x != nil && x.RemoteAddress != nil {
		return *x.RemoteAddress
	}
	return ""
}

var File_state_ble_proto protoreflect.FileDescriptor

const file_state_ble_proto_rawDesc = "" +
	"\n" +
	"\x0fstate/ble.proto\x12\rBSB_State.Ble\"z\n" +
	"\x03Ble\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.BSB_State.Ble.ServiceStatusR\x06status\x12*\n" +
	"\x0eremote_address\x18\x02 \x01(\tH\x00R\rremoteAddress\x88\x01\x01B\x11\n" +
	"\x0f_remote_address*u\n" +
	"\rServiceStatus\x12\t\n" +
	"\x05RESET\x10\x00\x12\x12\n" +
	"\x0eINITIALIZATION\x10\x01\x12\t\n" +
	"\x05READY\x10\x02\x12\x0f\n" +
	"\vADVERTISING\x10\x03\x12\x0f\n" +
	"\vCONNECTABLE\x10\x04\x12\r\n" +
	"\tCONNECTED\x10\x05\x12\t\n" +
	"\x05ERROR\x10\x06b\x06proto3"

var (
	file_state_ble_proto_rawDescOnce sync.Once
	file_state_ble_proto_rawDescData []byte
)

func file_state_ble_proto_rawDescGZIP() []byte {
	file_state_ble_proto_rawDescOnce.Do(func() {
		file_state_ble_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_ble_proto_rawDesc), len(file_state_ble_proto_rawDesc)))
	})
	return file_state_ble_proto_rawDescData
}

var file_state_ble_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_state_ble_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_state_ble_proto_goTypes = []any{
	(ServiceStatus)(0), // 0: BSB_State.Ble.ServiceStatus
	(*Ble)(nil),        // 1: BSB_State.Ble.Ble
}
var file_state_ble_proto_depIdxs = []int32{
	0, // 0: BSB_State.Ble.Ble.status:type_name -> BSB_State.Ble.ServiceStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_state_ble_proto_init() }
func file_state_ble_proto_init() {
	if File_state_ble_proto != nil {
		return
	}
	file_state_ble_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_ble_proto_rawDesc), len(file_state_ble_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_ble_proto_goTypes,
		DependencyIndexes: file_state_ble_proto_depIdxs,
		EnumInfos:         file_state_ble_proto_enumTypes,
		MessageInfos:      file_state_ble_proto_msgTypes,
	}.Build()
	File_state_ble_proto = out.File
	file_state_ble_proto_goTypes = nil
	file_state_ble_proto_depIdxs = nil
}
